/*
 * antirev stub launcher
 *
 * Appended-bundle format (at end of this binary after protection):
 *   [bundle_flags  : 1 B]        bit0 = main entry follows (BFLAG_HAS_MAIN)
 *                                bit1 = libs served by external daemon
 *   if BFLAG_HAS_MAIN:
 *     [name_len   : 2 B LE] [name : name_len bytes]
 *     [iv         : 12 B]
 *     [tag        : 16 B]
 *     [ct_size    : 8 B LE]
 *     [ciphertext : ct_size bytes]
 *   [bundle_start_offset : 8 B LE]   <- offset from file start
 *   [key  : 32 B]                    <- AES-256 key embedded in binary
 *   [magic : 8 B "ANTREV01"]
 *
 * Trailer is always 48 bytes at end of file.
 *
 * Operational modes:
 *
 *   A) Lightweight daemon (no main binary, no bundled libs):
 *      Scan own directory for encrypted .so files, decrypt into memfds,
 *      bind abstract socket, serve lib fds forever.  Centralized lib
 *      server so libs aren't duplicated in every exe.
 *
 *   B) Client exe (BFLAG_DAEMON_LIBS):
 *      Decrypt main exe only, connect to daemon to receive lib fds,
 *      then fexecve with those libs on LD_PRELOAD.
 *
 * Peak stub heap: one CHUNK_SIZE buffer (~4 MB) + header table (~37 KB max).
 * All plaintext lives only in kernel memfds, never fully in user-space heap.
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/syscall.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <sys/resource.h>
#include <sys/epoll.h>
#include <sys/eventfd.h>
#include <sys/mman.h>
#include <elf.h>
#include <dirent.h>
#include <pthread.h>
#include <time.h>
#include <signal.h>
#include "crypto.h"

#ifndef __NR_memfd_create
#  if defined(__x86_64__)
#    define __NR_memfd_create 319
#  elif defined(__aarch64__)
#    define __NR_memfd_create 279
#  endif
#endif

/* Generated by cmake — arch-specific shim blob.
 *
 * antirev_shim.so is the single LD_PRELOAD-able DSO shipped per arch.
 * It bundles the exe-identity interceptors (readlink, realpath,
 * getauxval …), the dlopen interceptor, and — on aarch64 — the
 * ANTI_LoadProcess hijack + popen/pclose override.  One memfd, one
 * LD_PRELOAD entry. */
#if defined(__aarch64__)
#include "antirev_shim_blob_aarch64.h" /* antirev_shim_blob,  antirev_shim_blob_len  */
#else
#include "antirev_shim_blob.h"
#endif

/* ------------------------------------------------------------------ */

#define MAGIC        "ANTREV01"
#define MAGIC_LEN    8
#define KEY_SIZE     32   /* AES-256 */
#define IV_SIZE      12   /* GCM nonce */
#define TAG_SIZE     16   /* GCM auth tag */
#define MAX_NAME     255
#define MAX_FILES    1024
#define CHUNK_SIZE   (16 * 1024 * 1024)  /* 16 MB I/O + crypto buffer */
#define SCM_BATCH    250  /* max fds per SCM_RIGHTS (kernel SCM_MAX_FD = 253) */

/* ------------------------------------------------------------------ */
/*  Per-file metadata collected during header scan (Phase 1)          */
/* ------------------------------------------------------------------ */
typedef struct {
    char name[MAX_NAME + 1];
    uint8_t  iv[IV_SIZE];
    uint8_t  tag[TAG_SIZE];
    uint64_t ct_size;
    uint64_t ct_offset;   /* byte offset in /proc/self/exe */
} file_entry_t;

/* ------------------------------------------------------------------ */
/*  Little-endian readers                                              */
/* ------------------------------------------------------------------ */
static inline uint16_t u16le(const uint8_t *p)
{
    return (uint16_t)(p[0] | (p[1] << 8));
}
static inline uint32_t u32le(const uint8_t *p)
{
    return p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint64_t u64le(const uint8_t *p)
{
    uint64_t v = 0;
    for (int i = 0; i < 8; i++) v |= (uint64_t)p[i] << (8 * i);
    return v;
}

/* ------------------------------------------------------------------ */
/*  Write bytes to a new memfd (no O_CLOEXEC — must survive fexecve)  */
/* ------------------------------------------------------------------ */
static int make_memfd(const char *name)
{
    int fd = (int)syscall(__NR_memfd_create, name, 0 /* no MFD_CLOEXEC */);
    if (fd < 0) { perror("memfd_create"); return -1; }
    return fd;
}

static int write_chunk(int fd, const uint8_t *data, size_t len)
{
    for (size_t w = 0; w < len; ) {
        ssize_t n = write(fd, data + w, len - w);
        if (n < 0) { perror("write memfd"); return -1; }
        w += (size_t)n;
    }
    return 0;
}

#define BFLAG_HAS_MAIN 0x01 /* one encrypted main entry follows the header */
#define BFLAG_DAEMON_LIBS 0x02 /* libs served by external daemon */

/* ------------------------------------------------------------------ */
/*  Daemon protocol v2                                                  */
/*                                                                      */
/*  Wire format (per message):                                          */
/*    [u32 op] [u32 payload_len] [payload bytes...]                    */
/*  plus optional SCM_RIGHTS ancillary data (OP_BATCH / OP_LIB only).   */
/*                                                                      */
/*  Client → Daemon:                                                    */
/*    OP_INIT     + [u32 nfilter] [(u16 nlen, bytes) * nfilter]        */
/*                  nfilter=0 means "send all libs".                    */
/*    OP_GET_LIB  + [u16 nlen] [name bytes]                            */
/*    OP_BYE      + (no payload) — daemon closes connection.           */
/*                                                                      */
/*  Daemon → Client (in response to OP_INIT):                           */
/*    Zero or more OP_BATCH messages, each with:                        */
/*      [u32 nlibs] [(u16 nlen, bytes) * nlibs]                        */
/*    and ancillary data: SCM_RIGHTS with nlibs fds.                    */
/*    Followed by a single OP_END message (empty payload) to mark EOF. */
/*                                                                      */
/*  Daemon → Client (in response to OP_GET_LIB):                        */
/*    OP_LIB + [u32 status]                                             */
/*    If status==ST_OK, ancillary SCM_RIGHTS carries 1 fd.              */
/*    If status!=ST_OK, no ancillary data.                              */
/* ------------------------------------------------------------------ */

#define OP_INIT         0x01u
#define OP_GET_LIB      0x02u
#define OP_BYE          0x03u
#define OP_LIST         0x04u  /* request: all lib names (no fds) */
#define OP_GET_CLOSURE  0x05u  /* request: lib + transitive encrypted deps */

#define OP_BATCH    0x81u
#define OP_END      0x82u
#define OP_LIB      0x83u
#define OP_NAMES    0x84u  /* response to OP_LIST: batched name list */

/* Per-lib adjacency cap.  Real business libs can DT_NEED 30+ entries
 * (system + Qt + boost + app libs) and anything beyond this cap gets
 * dropped from the deps graph, which then causes lazy fetch to miss
 * transitive encrypted deps and glibc to fall back to disk (hitting
 * ciphertext and aborting with "invalid elf header").  Keep this
 * well above the largest plausible DT_NEEDED list. */
#define MAX_DEPS_PER_LIB 128

/* Forward decl — defined with the other daemon helpers further below. */
static int compute_closure(const char *start,
                           const char (*lib_names)[MAX_NAME + 1], int nlibs,
                           int *out_idx, int max_out);

#define ST_OK        0u
#define ST_NOT_FOUND 1u
#define ST_ERROR     2u

/* Max payload bytes we will accept or send in one message.
 * Worst case: an OP_BATCH with SCM_BATCH entries, each up to MAX_NAME+2 bytes. */
#define MAX_PAYLOAD  (4u + SCM_BATCH * (2u + MAX_NAME))

static inline void put_u32le(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)(v & 0xff);
    p[1] = (uint8_t)((v >> 8) & 0xff);
    p[2] = (uint8_t)((v >> 16) & 0xff);
    p[3] = (uint8_t)((v >> 24) & 0xff);
}

static inline void put_u16le(uint8_t *p, uint16_t v)
{
    p[0] = (uint8_t)(v & 0xff);
    p[1] = (uint8_t)((v >> 8) & 0xff);
}

/* Blocking recv of exactly len bytes. Returns 0 on success, -1 on error/EOF. */
static int recv_full(int sock, void *buf, size_t len)
{
    size_t got = 0;
    while (got < len) {
        ssize_t n = recv(sock, (uint8_t *)buf + got, len - got, 0);
        if (n <= 0) {
            if (n < 0 && errno == EINTR) continue;
            return -1;
        }
        got += (size_t)n;
    }
    return 0;
}

/* Drain all SCM_RIGHTS fds we've already accepted into the caller's
 * array — used to clean up when a recv aborts mid-message after
 * cmsg unpacking succeeded.  Without this, callers see a -1 return
 * and assume nothing arrived; the fds end up stranded until process
 * exit reaps them. */
static void close_received_fds(int *fds, int *nfds)
{
    for (int i = 0; i < *nfds; i++) close(fds[i]);
    *nfds = 0;
}

/* Send one v2 message with optional ancillary fds.
 * Writes [u32 op | u32 plen | payload bytes] and, if nfds > 0,
 * attaches SCM_RIGHTS on the first sendmsg.
 * Returns 0 on success, -1 on failure. */
static int send_msg(int sock, uint32_t op, const void *payload, uint32_t plen,
                    const int *fds, int nfds)
{
    uint8_t hdr[8];
    put_u32le(hdr, op);
    put_u32le(hdr + 4, plen);

    struct iovec iov[2];
    iov[0].iov_base = hdr;
    iov[0].iov_len  = sizeof(hdr);
    iov[1].iov_base = (void *)payload;
    iov[1].iov_len  = plen;

    struct msghdr msg = {0};
    msg.msg_iov    = iov;
    msg.msg_iovlen = (plen > 0) ? 2 : 1;

    char cmsg_buf[CMSG_SPACE(SCM_BATCH * sizeof(int))];
    if (nfds > 0) {
        memset(cmsg_buf, 0, sizeof(cmsg_buf));
        msg.msg_control    = cmsg_buf;
        msg.msg_controllen = CMSG_SPACE((size_t)nfds * sizeof(int));
        struct cmsghdr *cm = CMSG_FIRSTHDR(&msg);
        cm->cmsg_level = SOL_SOCKET;
        cm->cmsg_type  = SCM_RIGHTS;
        cm->cmsg_len   = CMSG_LEN((size_t)nfds * sizeof(int));
        memcpy(CMSG_DATA(cm), fds, (size_t)nfds * sizeof(int));
    }

    size_t total = (size_t)8 + (size_t)plen;
    ssize_t n = sendmsg(sock, &msg, 0);
    if (n < 0) return -1;
    if ((size_t)n == total) return 0;

    /* Partial write after the first sendmsg: ancillary is already
     * delivered, finish the remaining bytes with plain send(). */
    size_t sent = (size_t)n;
    if (sent < 8) {
        size_t hrem = 8 - sent;
        ssize_t m = send(sock, hdr + sent, hrem, 0);
        if (m < 0 || (size_t)m != hrem) return -1;
        sent = 8;
    }
    size_t prem = total - sent;
    if (prem > 0) {
        ssize_t m = send(sock, (const uint8_t *)payload + (sent - 8), prem, 0);
        if (m < 0 || (size_t)m != prem) return -1;
    }
    return 0;
}

/* Receive one v2 message. On success sets *op and *plen, writes up to
 * *plen bytes into payload, and up to max_fds ancillary fds into fds[]
 * (setting *nfds). Returns 0 on success, -1 on error/EOF. */
static int recv_msg(int sock, uint32_t *op,
                    uint8_t *payload, uint32_t *plen, uint32_t max_payload,
                    int *fds, int *nfds, int max_fds)
{
    *nfds = 0;

    /* First recvmsg: 8-byte header + ancillary (if any). */
    uint8_t hdr[8];
    struct iovec iov = { .iov_base = hdr, .iov_len = sizeof(hdr) };

    char cmsg_buf[CMSG_SPACE(SCM_BATCH * sizeof(int))];
    memset(cmsg_buf, 0, sizeof(cmsg_buf));

    struct msghdr msg = {0};
    msg.msg_iov        = &iov;
    msg.msg_iovlen     = 1;
    msg.msg_control    = cmsg_buf;
    msg.msg_controllen = sizeof(cmsg_buf);

    ssize_t got = recvmsg(sock, &msg, 0);
    if (got <= 0) return -1;

    /* Extract any SCM_RIGHTS fds (attached to first byte of message). */
    for (struct cmsghdr *cm = CMSG_FIRSTHDR(&msg); cm; cm = CMSG_NXTHDR(&msg, cm)) {
        if (cm->cmsg_level == SOL_SOCKET && cm->cmsg_type == SCM_RIGHTS) {
            int n = (int)((cm->cmsg_len - CMSG_LEN(0)) / sizeof(int));
            if (n > max_fds) {
                int *src = (int *)CMSG_DATA(cm);
                for (int k = 0; k < n; k++) close(src[k]);
                return -1;
            }
            memcpy(fds, CMSG_DATA(cm), (size_t)n * sizeof(int));
            *nfds = n;
        }
    }

    /* Finish reading the header if we got fewer than 8 bytes. */
    if (got < (ssize_t)sizeof(hdr)) {
        if (recv_full(sock, hdr + got, sizeof(hdr) - (size_t)got) < 0) {
            close_received_fds(fds, nfds);
            return -1;
        }
    }

    *op = u32le(hdr);
    uint32_t p = u32le(hdr + 4);
    if (p > max_payload) {
        close_received_fds(fds, nfds);
        return -1;
    }
    *plen = p;

    if (p > 0) {
        if (recv_full(sock, payload, p) < 0) {
            close_received_fds(fds, nfds);
            return -1;
        }
    }
    return 0;
}

/* Build an OP_BATCH payload (u32 nlibs + per-lib u16 nlen + name bytes). */
static size_t build_batch_payload(uint8_t *buf, size_t buflen,
                                  const char (*names)[MAX_NAME + 1],
                                  int start, int count)
{
    if ((size_t)4 > buflen) return 0;
    put_u32le(buf, (uint32_t)count);
    size_t off = 4;
    for (int i = 0; i < count; i++) {
        uint16_t nlen = (uint16_t)strlen(names[start + i]);
        if (off + 2 + nlen > buflen) return 0;
        put_u16le(buf + off, nlen);
        off += 2;
        memcpy(buf + off, names[start + i], nlen);
        off += nlen;
    }
    return off;
}

/* Send the initial batch (filtered by `filter_names` if nfilter > 0, else all)
 * followed by OP_END. Returns 0 on success, -1 on failure. */
static int send_init_batch(int client, const int *lib_fds,
                           const char (*lib_names)[MAX_NAME + 1], int nlibs,
                           const char (*filter_names)[MAX_NAME + 1], int nfilter)
{
    /* Resolve selection: either the filter list, or the full lib list. */
    int   sel_fds[MAX_FILES];
    int   sel_count = 0;
    char  sel_names[MAX_FILES][MAX_NAME + 1];

    if (nfilter > 0) {
        for (int k = 0; k < nfilter; k++) {
            for (int j = 0; j < nlibs; j++) {
                if (strcmp(filter_names[k], lib_names[j]) == 0) {
                    sel_fds[sel_count] = lib_fds[j];
                    memcpy(sel_names[sel_count], lib_names[j], MAX_NAME + 1);
                    sel_count++;
                    break;
                }
            }
        }
    } else {
        sel_count = nlibs;
        memcpy(sel_fds, lib_fds, (size_t)nlibs * sizeof(int));
        memcpy(sel_names, lib_names, (size_t)nlibs * (MAX_NAME + 1));
    }

    /* Send in SCM_BATCH-sized chunks. */
    for (int off = 0; off < sel_count; off += SCM_BATCH) {
        int batch = sel_count - off;
        if (batch > SCM_BATCH) batch = SCM_BATCH;

        uint8_t payload[MAX_PAYLOAD];
        size_t plen = build_batch_payload(payload, sizeof(payload),
                                          sel_names, off, batch);
        if (plen == 0) return -1;
        if (send_msg(client, OP_BATCH, payload, (uint32_t)plen,
                     sel_fds + off, batch) < 0)
            return -1;
    }
    return send_msg(client, OP_END, NULL, 0, NULL, 0);
}

/* Handle OP_GET_LIB: look up `name` in the daemon's lib table and reply
 * with OP_LIB + status + (optionally) one fd. */
static int handle_get_lib(int client, const int *lib_fds,
                          const char (*lib_names)[MAX_NAME + 1], int nlibs,
                          const uint8_t *payload, uint32_t plen)
{
    uint8_t resp[4];
    if (plen < 2) {
        put_u32le(resp, ST_ERROR);
        return send_msg(client, OP_LIB, resp, 4, NULL, 0);
    }
    uint16_t nlen;
    memcpy(&nlen, payload, 2);
    if ((uint32_t)nlen + 2u > plen || nlen > MAX_NAME) {
        put_u32le(resp, ST_ERROR);
        return send_msg(client, OP_LIB, resp, 4, NULL, 0);
    }
    char name[MAX_NAME + 1];
    memcpy(name, payload + 2, nlen);
    name[nlen] = '\0';

    for (int j = 0; j < nlibs; j++) {
        if (strcmp(lib_names[j], name) == 0) {
            put_u32le(resp, ST_OK);
            int fd = lib_fds[j];
            return send_msg(client, OP_LIB, resp, 4, &fd, 1);
        }
    }
    put_u32le(resp, ST_NOT_FOUND);
    return send_msg(client, OP_LIB, resp, 4, NULL, 0);
}

/* Handle OP_LIST: reply with all lib names in SCM_BATCH-sized OP_NAMES
 * messages, terminated by OP_END. No fds attached. */
static int handle_list(int client,
                       const char (*lib_names)[MAX_NAME + 1], int nlibs)
{
    for (int off = 0; off < nlibs; off += SCM_BATCH) {
        int batch = nlibs - off;
        if (batch > SCM_BATCH) batch = SCM_BATCH;
        uint8_t payload[MAX_PAYLOAD];
        size_t plen = build_batch_payload(payload, sizeof(payload),
                                          lib_names, off, batch);
        if (plen == 0) return -1;
        if (send_msg(client, OP_NAMES, payload, (uint32_t)plen, NULL, 0) < 0)
            return -1;
    }
    return send_msg(client, OP_END, NULL, 0, NULL, 0);
}

/* Handle OP_GET_CLOSURE: compute transitive encrypted closure of the
 * requested lib (via build_deps_graph'd adjacency), then reply with
 * OP_BATCH(es) carrying (fd, name) for every lib in the closure,
 * terminated by OP_END.  If the name is not in the daemon's lib set,
 * replies with a single OP_END (empty closure). */
static int handle_get_closure(int client, const int *lib_fds,
                              const char (*lib_names)[MAX_NAME + 1], int nlibs,
                              const uint8_t *payload, uint32_t plen)
{
    if (plen < 2)
        return send_msg(client, OP_END, NULL, 0, NULL, 0);
    uint16_t nlen;
    memcpy(&nlen, payload, 2);
    if ((uint32_t)nlen + 2u > plen || nlen > MAX_NAME)
        return send_msg(client, OP_END, NULL, 0, NULL, 0);
    char name[MAX_NAME + 1];
    memcpy(name, payload + 2, nlen);
    name[nlen] = '\0';

    int closure[MAX_FILES];
    int n = compute_closure(name, lib_names, nlibs, closure, MAX_FILES);
    if (n <= 0)
        return send_msg(client, OP_END, NULL, 0, NULL, 0);

    /* Materialize ordered fds/names for the batch sender. */
    int  sel_fds[MAX_FILES];
    char sel_names[MAX_FILES][MAX_NAME + 1];
    for (int i = 0; i < n; i++) {
        sel_fds[i] = lib_fds[closure[i]];
        memcpy(sel_names[i], lib_names[closure[i]], MAX_NAME + 1);
    }

    for (int off = 0; off < n; off += SCM_BATCH) {
        int batch = n - off;
        if (batch > SCM_BATCH) batch = SCM_BATCH;
        uint8_t pay[MAX_PAYLOAD];
        size_t pl = build_batch_payload(pay, sizeof(pay), sel_names, off, batch);
        if (pl == 0) return -1;
        if (send_msg(client, OP_BATCH, pay, (uint32_t)pl,
                     sel_fds + off, batch) < 0)
            return -1;
    }
    return send_msg(client, OP_END, NULL, 0, NULL, 0);
}

/* Parse an OP_INIT payload into a filter list. Returns number of names,
 * or -1 on parse error. */
static int parse_init_filter(const uint8_t *payload, uint32_t plen,
                             char (*out_names)[MAX_NAME + 1])
{
    if (plen < 4) return -1;
    uint32_t nfilter = u32le(payload);
    if (nfilter > MAX_FILES) return -1;
    size_t off = 4;
    for (uint32_t i = 0; i < nfilter; i++) {
        if (off + 2 > plen) return -1;
        uint16_t nlen;
        memcpy(&nlen, payload + off, 2);
        off += 2;
        if (nlen > MAX_NAME || off + nlen > plen) return -1;
        memcpy(out_names[i], payload + off, nlen);
        out_names[i][nlen] = '\0';
        off += nlen;
    }
    return (int)nfilter;
}

/* Process a single inbound request from a connected client.
 * Returns 0 to keep the connection alive, -1 to close it. */
static int daemon_handle_request(int client, const int *lib_fds,
                                 const char (*lib_names)[MAX_NAME + 1], int nlibs)
{
    uint32_t op, plen;
    uint8_t  payload[MAX_PAYLOAD];
    int      dummy_fds[1];
    int      dummy_nfds = 0;

    if (recv_msg(client, &op, payload, &plen, MAX_PAYLOAD,
                 dummy_fds, &dummy_nfds, 0) < 0)
        return -1;

    if (op == OP_INIT) {
        char filter[MAX_FILES][MAX_NAME + 1];
        int  nfilter = parse_init_filter(payload, plen, filter);
        if (nfilter < 0) return -1;
        return send_init_batch(client, lib_fds, lib_names, nlibs,
                               filter, nfilter);
    }
    if (op == OP_GET_LIB) {
        return handle_get_lib(client, lib_fds, lib_names, nlibs, payload, plen);
    }
    if (op == OP_LIST) {
        return handle_list(client, lib_names, nlibs);
    }
    if (op == OP_GET_CLOSURE) {
        return handle_get_closure(client, lib_fds, lib_names, nlibs,
                                  payload, plen);
    }
    if (op == OP_BYE) {
        return -1;
    }
    return -1;
}

/* Single-threaded epoll-based serve loop.  Runs as the daemon's worker
 * thread (see run_daemon_forever); the main thread parks in sigwait()
 * and writes to shutdown_efd on SIGTERM/INT/HUP/QUIT.  When the worker
 * sees the eventfd fire it returns, the main thread then joins and
 * tears down everything passed in.
 *
 * Same-uid check enforced at accept.  Client fds are tracked in a
 * fixed-size table so they can all be closed when the loop exits. */
#define DAEMON_MAX_CLIENTS 256

static void daemon_serve(int listen_fd, int shutdown_efd, const int *lib_fds,
                         const char (*lib_names)[MAX_NAME + 1], int nlibs)
{
    uid_t my_uid = getuid();

    int ep = epoll_create1(EPOLL_CLOEXEC);
    if (ep < 0) return;

    struct epoll_event lev = { .events = EPOLLIN, .data.fd = listen_fd };
    if (epoll_ctl(ep, EPOLL_CTL_ADD, listen_fd, &lev) < 0) {
        close(ep);
        return;
    }
    struct epoll_event sev = { .events = EPOLLIN, .data.fd = shutdown_efd };
    if (epoll_ctl(ep, EPOLL_CTL_ADD, shutdown_efd, &sev) < 0) {
        close(ep);
        return;
    }

    int clients[DAEMON_MAX_CLIENTS];
    for (int i = 0; i < DAEMON_MAX_CLIENTS; i++) clients[i] = -1;

    int running = 1;
    struct epoll_event evs[32];
    while (running) {
        int n = epoll_wait(ep, evs, 32, -1);
        if (n < 0) {
            if (errno == EINTR) continue;
            break;
        }

        for (int i = 0; i < n; i++) {
            int fd = evs[i].data.fd;

            if (fd == shutdown_efd) {
                running = 0;
                break;
            }

            if (fd == listen_fd) {
                int client = accept4(listen_fd, NULL, NULL, SOCK_CLOEXEC);
                if (client < 0) continue;

                struct ucred cred;
                socklen_t clen = sizeof(cred);
                if (getsockopt(client, SOL_SOCKET, SO_PEERCRED, &cred, &clen) < 0
                    || cred.uid != my_uid) {
                    close(client);
                    continue;
                }

                struct epoll_event cev = { .events = EPOLLIN | EPOLLRDHUP, .data.fd = client };
                if (epoll_ctl(ep, EPOLL_CTL_ADD, client, &cev) < 0) {
                    close(client);
                    continue;
                }
                /* Track for shutdown close.  Overflow → still served,
                 * just not tracked; the kernel reaps it on _exit. */
                for (int k = 0; k < DAEMON_MAX_CLIENTS; k++) {
                    if (clients[k] == -1) { clients[k] = client; break; }
                }
                continue;
            }

            if (evs[i].events & (EPOLLHUP | EPOLLRDHUP | EPOLLERR)) {
                epoll_ctl(ep, EPOLL_CTL_DEL, fd, NULL);
                close(fd);
                for (int k = 0; k < DAEMON_MAX_CLIENTS; k++) {
                    if (clients[k] == fd) { clients[k] = -1; break; }
                }
                continue;
            }

            if (evs[i].events & EPOLLIN) {
                if (daemon_handle_request(fd, lib_fds, lib_names, nlibs) < 0) {
                    epoll_ctl(ep, EPOLL_CTL_DEL, fd, NULL);
                    close(fd);
                    for (int k = 0; k < DAEMON_MAX_CLIENTS; k++) {
                        if (clients[k] == fd) { clients[k] = -1; break; }
                    }
                }
            }
        }
    }

    /* Shutdown: close every fd we created internally.  listen_fd,
     * shutdown_efd, and lib_fds belong to the caller and are torn
     * down by the main thread after pthread_join. */
    for (int i = 0; i < DAEMON_MAX_CLIENTS; i++)
        if (clients[i] >= 0) close(clients[i]);
    close(ep);
}

struct daemon_serve_args {
    int listen_fd;
    int shutdown_efd;
    const int *lib_fds;
    const char (*lib_names)[MAX_NAME + 1];
    int nlibs;
};

static void *daemon_serve_thread(void *arg)
{
    struct daemon_serve_args *a = (struct daemon_serve_args *)arg;
    daemon_serve(a->listen_fd, a->shutdown_efd, a->lib_fds, a->lib_names, a->nlibs);
    /* If daemon_serve returned (setup error like epoll_create1
     * failure, or normal shutdown after the eventfd fired), make
     * sure the main thread's sigwait() also wakes — otherwise on
     * a worker setup failure the daemon would hang forever waiting
     * for an external signal.  kill(getpid(), SIGTERM) queues a
     * process-targeted signal; SIGTERM is blocked in both threads
     * so it lands wherever sigwait is parked.  Redundant on the
     * normal-shutdown path (main is no longer in sigwait by then),
     * harmless either way. */
    kill(getpid(), SIGTERM);
    return NULL;
}

/* Client-side helper: send OP_INIT (optionally with a filter list),
 * collect all OP_BATCH messages until OP_END, return fds + names.
 * If nfilter == 0, requests the full lib set.
 * Returns 0 on success, -1 on failure. */
static int daemon_request_libs(int sd,
                               const char (*filter_names)[MAX_NAME + 1],
                               int nfilter,
                               int *out_fds,
                               char (*out_names)[MAX_NAME + 1],
                               int *out_nlibs)
{
    /* Build OP_INIT payload: [u32 nfilter] [(u16 nlen, bytes) * nfilter] */
    uint8_t init_payload[MAX_PAYLOAD];
    put_u32le(init_payload, (uint32_t)nfilter);
    size_t off = 4;
    for (int i = 0; i < nfilter; i++) {
        uint16_t nlen = (uint16_t)strlen(filter_names[i]);
        if (off + 2 + nlen > sizeof(init_payload)) return -1;
        put_u16le(init_payload + off, nlen);
        off += 2;
        memcpy(init_payload + off, filter_names[i], nlen);
        off += nlen;
    }
    if (send_msg(sd, OP_INIT, init_payload, (uint32_t)off, NULL, 0) < 0)
        return -1;

    *out_nlibs = 0;
    for (;;) {
        uint32_t op, plen;
        uint8_t  payload[MAX_PAYLOAD];
        int      recvd_fds[SCM_BATCH];
        int      nrecvd = 0;

        if (recv_msg(sd, &op, payload, &plen, MAX_PAYLOAD,
                     recvd_fds, &nrecvd, SCM_BATCH) < 0)
            return -1;

        if (op == OP_END) break;
        /* Any framing / parse failure below this point must close
         * the fds we already accepted via SCM_RIGHTS, otherwise they
         * leak when daemon_connect_and_fetch closes the socket and
         * returns.  out_fds aliases recvd_fds after the memcpy below
         * (same int values, no kernel ref bump), so closing recvd_fds
         * is sufficient. */
        if (op != OP_BATCH) {
            close_received_fds(recvd_fds, &nrecvd);
            return -1;
        }
        if (plen < 4) {
            close_received_fds(recvd_fds, &nrecvd);
            return -1;
        }

        uint32_t nl = u32le(payload);
        if ((int)nl != nrecvd) {
            close_received_fds(recvd_fds, &nrecvd);
            return -1;
        }
        if (*out_nlibs + (int)nl > MAX_FILES) {
            close_received_fds(recvd_fds, &nrecvd);
            return -1;
        }

        memcpy(out_fds + *out_nlibs, recvd_fds, (size_t)nl * sizeof(int));

        size_t poff = 4;
        for (uint32_t i = 0; i < nl; i++) {
            if (poff + 2 > plen) {
                close_received_fds(recvd_fds, &nrecvd);
                return -1;
            }
            uint16_t nlen;
            memcpy(&nlen, payload + poff, 2);
            poff += 2;
            if (nlen > MAX_NAME || poff + nlen > plen) {
                close_received_fds(recvd_fds, &nrecvd);
                return -1;
            }
            memcpy(out_names[*out_nlibs + (int)i], payload + poff, nlen);
            out_names[*out_nlibs + (int)i][nlen] = '\0';
            poff += nlen;
        }
        *out_nlibs += (int)nl;
    }
    return (*out_nlibs > 0) ? 0 : -1;
}

/* Client-side helper: send OP_LIST and collect OP_NAMES/OP_END to recover
 * the full set of encrypted lib names the daemon manages. No fds.
 * Returns 0 on success, -1 on error. */
static int daemon_request_names(int sd,
                                char (*out_names)[MAX_NAME + 1],
                                int *out_nlibs)
{
    if (send_msg(sd, OP_LIST, NULL, 0, NULL, 0) < 0) return -1;
    *out_nlibs = 0;
    for (;;) {
        uint32_t op, plen;
        uint8_t  payload[MAX_PAYLOAD];
        int      dummy_fds[1];
        int      nrecvd = 0;
        if (recv_msg(sd, &op, payload, &plen, MAX_PAYLOAD,
                     dummy_fds, &nrecvd, 0) < 0)
            return -1;
        if (op == OP_END) break;
        if (op != OP_NAMES) return -1;
        if (plen < 4) return -1;
        uint32_t nl = u32le(payload);
        size_t poff = 4;
        for (uint32_t i = 0; i < nl; i++) {
            if (poff + 2 > plen) return -1;
            uint16_t nlen;
            memcpy(&nlen, payload + poff, 2);
            poff += 2;
            if (nlen > MAX_NAME || poff + nlen > plen) return -1;
            if (*out_nlibs >= MAX_FILES) return -1;
            memcpy(out_names[*out_nlibs], payload + poff, nlen);
            out_names[*out_nlibs][nlen] = '\0';
            (*out_nlibs)++;
            poff += nlen;
        }
    }
    return 0;
}

/* Send OP_GET_LIB and receive one OP_LIB response with a single fd.
 * Returns the fd on success, -1 on error. Used by lazy-fetch in dlopen_shim. */
__attribute__((unused))
static int daemon_request_one(int sd, const char *name)
{
    uint16_t nlen = (uint16_t)strlen(name);
    if (nlen > MAX_NAME) return -1;

    uint8_t req[2 + MAX_NAME];
    put_u16le(req, nlen);
    memcpy(req + 2, name, nlen);
    if (send_msg(sd, OP_GET_LIB, req, (uint32_t)(2 + nlen), NULL, 0) < 0)
        return -1;

    uint32_t op, plen;
    uint8_t  payload[16];
    int      recvd_fds[1];
    int      nrecvd = 0;
    if (recv_msg(sd, &op, payload, &plen, sizeof(payload),
                 recvd_fds, &nrecvd, 1) < 0)
        return -1;
    if (op != OP_LIB || plen < 4) {
        close_received_fds(recvd_fds, &nrecvd);
        return -1;
    }
    uint32_t status = u32le(payload);
    if (status != ST_OK || nrecvd != 1) {
        close_received_fds(recvd_fds, &nrecvd);
        return -1;
    }
    return recvd_fds[0];
}

/* Send OP_BYE to cleanly close the daemon socket. Best-effort. */
static void daemon_send_bye(int sd)
{
    (void)send_msg(sd, OP_BYE, NULL, 0, NULL, 0);
}

/* Build abstract socket address from key hash.
 * Returns the sockaddr_un length to pass to bind/connect. */
static socklen_t make_sock_addr(struct sockaddr_un *addr,
                                const uint8_t key[KEY_SIZE])
{
    /* Derive socket name: AES_K(0^128)[0:8] → hex.
     * This is the GHASH subkey H, deterministic per key. */
    aes256gcm_ctx tmp;
    uint8_t dummy_iv[IV_SIZE] = {0};
    aes256gcm_init(&tmp, key, dummy_iv);
    /* tmp.H now contains AES_K(0^128) */

    char hex[17];
    for (int i = 0; i < 8; i++)
        snprintf(hex + i * 2, 3, "%02x", tmp.H[i]);

    memset(addr, 0, sizeof(*addr));
    addr->sun_family = AF_UNIX;
    /* Abstract socket: sun_path[0] = '\0' (already zeroed), name follows */
    snprintf(addr->sun_path + 1, sizeof(addr->sun_path) - 1,
             "antirev_%s", hex);

    explicit_bzero(&tmp, sizeof(tmp));

    return (socklen_t)(offsetof(struct sockaddr_un, sun_path)
                       + 1 + strlen(addr->sun_path + 1));
}

/* ------------------------------------------------------------------ */
/*  ELF DT_NEEDED parser + per-lib dependency graph (daemon-side)     */
/*                                                                      */
/*  At daemon startup we mmap each decrypted lib memfd, parse its      */
/*  PT_DYNAMIC segment, extract DT_NEEDED names, and filter them to    */
/*  the set of encrypted libs the daemon manages.  The resulting       */
/*  adjacency list is later used by compute_closure() to answer        */
/*  OP_GET_CLOSURE requests — so dlopen_shim can fetch a lib and its   */
/*  transitive encrypted deps in a single round-trip.                  */
/* ------------------------------------------------------------------ */

static int  g_deps_count[MAX_FILES];
static int  g_deps_idx[MAX_FILES][MAX_DEPS_PER_LIB];

/* Bounds-check an ELF64 header and phdr table against the mapped size.
 * Returns 0 on a usable ELF64, -1 otherwise. */
static int elf64_header_ok(const Elf64_Ehdr *eh, size_t size) {
    if (memcmp(eh->e_ident, ELFMAG, SELFMAG) != 0)
        return -1;
    if (eh->e_ident[EI_CLASS] != ELFCLASS64)
        return -1;
    if (eh->e_phoff + (uint64_t) eh->e_phnum * eh->e_phentsize > (uint64_t) size)
        return -1;
    return 0;
}

/* Scan program headers for PT_DYNAMIC.  Returns pointer or NULL. */
static const Elf64_Phdr *find_pt_dynamic(const Elf64_Phdr *phdrs, int phnum) {
    for (int i = 0; i < phnum; i++)
        if (phdrs[i].p_type == PT_DYNAMIC)
            return &phdrs[i];
    return NULL;
}

/* Find the DT_STRTAB vaddr in .dynamic.  Returns 0 if absent. */
static uint64_t find_dt_strtab_vaddr(const Elf64_Dyn *dyn, int ndyn) {
    for (int i = 0; i < ndyn; i++) {
        if (dyn[i].d_tag == DT_NULL)
            return 0;
        if (dyn[i].d_tag == DT_STRTAB)
            return dyn[i].d_un.d_ptr;
    }
    return 0;
}

/* Map a runtime vaddr back to its file offset via PT_LOAD segments.
 * Returns -1 if the vaddr isn't covered by any loadable segment. */
static off_t vaddr_to_file_offset(const Elf64_Phdr *phdrs, int phnum, uint64_t vaddr) {
    for (int i = 0; i < phnum; i++) {
        if (phdrs[i].p_type != PT_LOAD)
            continue;
        if (vaddr >= phdrs[i].p_vaddr && vaddr < phdrs[i].p_vaddr + phdrs[i].p_memsz)
            return (off_t) (vaddr - phdrs[i].p_vaddr + phdrs[i].p_offset);
    }
    return -1;
}

/* Walk .dynamic collecting DT_NEEDED names into out[0..max_out-1].
 * Returns the stored count; *total_observed gets the full DT_NEEDED
 * count so the caller can detect truncation. */
static int collect_dt_needed_names(const Elf64_Dyn *dyn, int ndyn, const char *strtab, size_t strtab_max,
                                   char (*out)[MAX_NAME + 1], int max_out, int *total_observed) {
    int n = 0, total = 0;
    for (int i = 0; i < ndyn; i++) {
        if (dyn[i].d_tag == DT_NULL)
            break;
        if (dyn[i].d_tag != DT_NEEDED)
            continue;
        total++;
        if (n >= max_out)
            continue; /* cap reached — keep counting for truncation signal */
        uint64_t off = dyn[i].d_un.d_val;
        if (off >= strtab_max)
            continue;
        size_t len = strnlen(strtab + off, strtab_max - off);
        if (len == 0 || len > MAX_NAME)
            continue;
        memcpy(out[n], strtab + off, len);
        out[n][len] = '\0';
        n++;
    }
    *total_observed = total;
    return n;
}

/* Parse an ELF64 shared lib's DT_NEEDED list from the mapped image.
 * Returns the number of names written, or -1 on parse failure.
 * Caller-facing truncation handling happens in parse_dt_needed(). */
static int parse_dt_needed_mapped(const uint8_t *base, size_t size, char (*out)[MAX_NAME + 1], int max_out,
                                  int *total_observed) {
    const Elf64_Ehdr *eh = (const Elf64_Ehdr *) base;
    if (elf64_header_ok(eh, size) < 0)
        return -1;

    const Elf64_Phdr *phdrs = (const Elf64_Phdr *) (base + eh->e_phoff);
    const Elf64_Phdr *dyn_ph = find_pt_dynamic(phdrs, eh->e_phnum);
    if (!dyn_ph || dyn_ph->p_offset + dyn_ph->p_filesz > (uint64_t) size)
        return -1;

    const Elf64_Dyn *dyn = (const Elf64_Dyn *) (base + dyn_ph->p_offset);
    int ndyn = (int) (dyn_ph->p_filesz / sizeof(Elf64_Dyn));

    uint64_t strtab_vaddr = find_dt_strtab_vaddr(dyn, ndyn);
    if (!strtab_vaddr)
        return -1;

    off_t strtab_off = vaddr_to_file_offset(phdrs, eh->e_phnum, strtab_vaddr);
    if (strtab_off < 0 || strtab_off >= (off_t) size)
        return -1;

    const char *strtab = (const char *) (base + strtab_off);
    size_t strtab_max = size - (size_t) strtab_off;

    return collect_dt_needed_names(dyn, ndyn, strtab, strtab_max, out, max_out, total_observed);
}

/* Parse an ELF64 fd's DT_NEEDED list.  Positive return = full list fits.
 * Negative return = -total (truncation signal: caller should grow
 * MAX_DEPS_PER_LIB).  -1 = parse failure (not ELF64, stripped, etc.). */
static int parse_dt_needed(int fd, char (*out_names)[MAX_NAME + 1], int max_out) {
    struct stat st;
    if (fstat(fd, &st) < 0 || st.st_size < (off_t) sizeof(Elf64_Ehdr))
        return -1;

    void *map = mmap(NULL, (size_t) st.st_size, PROT_READ, MAP_PRIVATE, fd, 0);
    if (map == MAP_FAILED)
        return -1;

    int total = 0;
    int n = parse_dt_needed_mapped((const uint8_t *) map, (size_t) st.st_size, out_names, max_out, &total);
    munmap(map, (size_t)st.st_size);

    if (n < 0)
        return -1;
    return (total > max_out) ? -total : n;
}

/* Build per-lib adjacency list: for each lib, record indices of its
 * direct DT_NEEDED deps that are also in the daemon's lib table.
 * Libs whose deps can't be parsed (stripped, etc.) get deps_count = 0. */
static void build_deps_graph(const int *lib_fds,
                             const char (*lib_names)[MAX_NAME + 1], int nlibs)
{
    char dt_names[MAX_DEPS_PER_LIB][MAX_NAME + 1];
    for (int i = 0; i < nlibs; i++) {
        g_deps_count[i] = 0;
        int n_dt = parse_dt_needed(lib_fds[i], dt_names, MAX_DEPS_PER_LIB);
        if (n_dt == -1) {
            /* Parse failure (no PT_DYNAMIC, ELF32, no DT_STRTAB, etc.)
             * — treat as zero deps.  Common and benign for .elf PG
             * binaries and statically-linked libs. */
            continue;
        }
        if (n_dt < -1) {
            /* Truncation: parse_dt_needed returns -(total) when the
             * total DT_NEEDED count exceeded MAX_DEPS_PER_LIB.  This
             * is bad for lazy closure fetch — any dropped encrypted
             * dep will send glibc to disk at load time and abort
             * with "invalid elf header".  Bump the cap and rebuild. */
            int total = -n_dt;
            fprintf(stderr, "[antirev] WARNING: %s has %d DT_NEEDED "
                    "entries, only %d captured (MAX_DEPS_PER_LIB=%d). "
                    "Increase the cap.\n",
                    lib_names[i], total, MAX_DEPS_PER_LIB,
                    MAX_DEPS_PER_LIB);
            n_dt = MAX_DEPS_PER_LIB;
        }
        if (n_dt == 0) continue;
        for (int k = 0; k < n_dt; k++) {
            for (int j = 0; j < nlibs; j++) {
                if (j == i) continue;
                if (strcmp(lib_names[j], dt_names[k]) == 0) {
                    if (g_deps_count[i] < MAX_DEPS_PER_LIB)
                        g_deps_idx[i][g_deps_count[i]++] = j;
                    break;
                }
            }
        }
    }
}

/* Iterative DFS post-order from `node` through the encrypted-deps graph.
 * Emits each lib AFTER all its transitive deps — giving the client a
 * topological ordering (leaves first, root last) it can replay via
 * real_dlopen() so each lib finds its already-loaded deps in glibc's
 * link map and skips DT_RPATH / DT_RUNPATH search on disk. */
static void dfs_postorder(int start_idx, uint8_t *visited,
                          int *out_idx, int *n_out, int max_out)
{
    /* Stack frame: (node, next-child-index-to-visit).  We push the node
     * when first encountered, keep visiting its unexplored deps, and
     * emit it once the child index runs off the end. */
    int stack_node[MAX_FILES];
    int stack_next[MAX_FILES];
    int top = 0;

    if (visited[start_idx]) return;
    visited[start_idx] = 1;
    stack_node[top] = start_idx;
    stack_next[top] = 0;
    top++;

    while (top > 0) {
        int node = stack_node[top - 1];
        int next = stack_next[top - 1];

        if (next >= g_deps_count[node]) {
            /* All children visited: emit this node and pop. */
            if (*n_out < max_out) out_idx[(*n_out)++] = node;
            top--;
            continue;
        }
        stack_next[top - 1] = next + 1;
        int dep = g_deps_idx[node][next];
        if (!visited[dep] && top < MAX_FILES) {
            visited[dep] = 1;
            stack_node[top] = dep;
            stack_next[top] = 0;
            top++;
        }
    }
}

/* Topological closure from a lib name through the encrypted-deps graph.
 * Writes indices into out_idx[] in deps-first order, returns count
 * (>= 1 on success) or -1 if `start` is not in the lib table. */
static int compute_closure(const char *start,
                           const char (*lib_names)[MAX_NAME + 1], int nlibs,
                           int *out_idx, int max_out)
{
    int start_idx = -1;
    for (int i = 0; i < nlibs; i++) {
        if (strcmp(lib_names[i], start) == 0) { start_idx = i; break; }
    }
    if (start_idx < 0) return -1;

    static uint8_t visited[MAX_FILES];
    memset(visited, 0, sizeof(visited));
    int n_out = 0;
    dfs_postorder(start_idx, visited, out_idx, &n_out, max_out);
    return n_out;
}

/* ------------------------------------------------------------------ */
/*  Decrypt standalone encrypted file from disk                        */
/*  Format: ANTREV01(8) + iv(12) + tag(16) + ciphertext               */
/*  Returns memfd on success, -1 on failure.                           */
/* ------------------------------------------------------------------ */
static int decrypt_enc_file(const char *path, const uint8_t *key,
                            uint8_t *chunk)
{
    int fd = open(path, O_RDONLY);
    if (fd < 0) return -1;

    uint8_t hdr[MAGIC_LEN + IV_SIZE + TAG_SIZE]; /* 36 bytes */
    if (pread(fd, hdr, sizeof(hdr), 0) != (ssize_t)sizeof(hdr)
        || memcmp(hdr, MAGIC, MAGIC_LEN) != 0) {
        close(fd);
        return -1;
    }

    uint8_t *iv  = hdr + MAGIC_LEN;
    uint8_t *tag = hdr + MAGIC_LEN + IV_SIZE;

    off_t fsize = lseek(fd, 0, SEEK_END);
    off_t ct_off = (off_t)sizeof(hdr);
    uint64_t ct_size = (uint64_t)(fsize - ct_off);
    if (ct_size == 0) { close(fd); return -1; }

    const char *bname = strrchr(path, '/');
    bname = bname ? bname + 1 : path;

    int mfd = make_memfd(bname);
    if (mfd < 0) { close(fd); return -1; }

    aes256gcm_ctx ctx;

    /* Single pass: GHASH + CTR simultaneously (halves disk I/O) */
    aes256gcm_init(&ctx, key, iv);
    uint64_t remaining = ct_size;
    off_t pos = ct_off;
    while (remaining > 0) {
        size_t  to_read = (remaining < CHUNK_SIZE) ? (size_t)remaining : CHUNK_SIZE;
        ssize_t got     = pread(fd, chunk, to_read, pos);
        if (got != (ssize_t)to_read) { close(fd); close(mfd); return -1; }
        aes256gcm_onepass(&ctx, chunk, chunk, to_read);
        if (write_chunk(mfd, chunk, to_read) != 0) { close(fd); close(mfd); return -1; }
        pos       += (off_t)to_read;
        remaining -= to_read;
    }
    if (aes256gcm_ghash_verify(&ctx, tag) != 0) {
        if (ftruncate(mfd, 0)) { /* wipe plaintext */ }
        close(fd); close(mfd);
        return -1;
    }
    if (lseek(mfd, 0, SEEK_SET) < 0) { close(fd); close(mfd); return -1; }

    close(fd);
    return mfd;
}

/* ------------------------------------------------------------------ */
/*  Parallel decryption of encrypted .so files from disk               */
/* ------------------------------------------------------------------ */

/* Per-file decryption job */
typedef struct {
    char     path[4096];
    char     name[MAX_NAME + 1];
    const uint8_t *key;
    int      fd;      /* result memfd, -1 on failure */
} dec_job_t;

/* Work-stealing pool: each thread grabs next available job */
typedef struct {
    dec_job_t   *jobs;
    int          njobs;
    volatile int next;   /* atomic counter for work stealing */
} dec_pool_t;

static void *pool_worker(void *arg)
{
    dec_pool_t *pool = (dec_pool_t *)arg;
    uint8_t *chunk = malloc(CHUNK_SIZE);
    if (!chunk) return NULL;

    for (;;) {
        int idx = __sync_fetch_and_add(&pool->next, 1);
        if (idx >= pool->njobs) break;
        pool->jobs[idx].fd = decrypt_enc_file(pool->jobs[idx].path,
                                               pool->jobs[idx].key, chunk);
    }

    explicit_bzero(chunk, CHUNK_SIZE);
    free(chunk);
    return NULL;
}

/* Recursively collect paths of encrypted .so / .elf files (ANTREV01 magic).
 *
 * The extension check is a fast-path filter so we do not open every
 * regular file in the tree to test for our magic — the real
 * authoritative filter is the magic-byte check below.  .elf files
 * are program binaries consumed by ANTI_LoadProcess (served to aarch64_extend_shim
 * via OP_GET_LIB) and coexist with .so libs in the same asset pool. */
static void collect_enc_paths(const char *dir, dec_job_t *jobs, int *njobs,
                              int max)
{
    DIR *dp = opendir(dir);
    if (!dp) return;

    struct dirent *de;
    while ((de = readdir(dp)) != NULL && *njobs < max) {
        if (de->d_name[0] == '.') continue;

        char path[4096];
        snprintf(path, sizeof(path), "%s/%s", dir, de->d_name);

        struct stat st;
        if (lstat(path, &st) != 0) continue;
        if (S_ISLNK(st.st_mode)) continue;  /* skip symlinks — avoid dupes */

        if (S_ISDIR(st.st_mode)) {
            collect_enc_paths(path, jobs, njobs, max);
            continue;
        }
        if (!S_ISREG(st.st_mode)) continue;
        if (!strstr(de->d_name, ".so") && !strstr(de->d_name, ".elf")) continue;

        /* Skip duplicate filenames (same lib in different subdirs) */
        int dup = 0;
        for (int i = 0; i < *njobs; i++) {
            if (strcmp(jobs[i].name, de->d_name) == 0) { dup = 1; break; }
        }
        if (dup) continue;

        /* Quick magic check — avoids queuing non-encrypted files */
        int fd = open(path, O_RDONLY);
        if (fd < 0) continue;
        uint8_t magic[MAGIC_LEN];
        int is_enc = (read(fd, magic, MAGIC_LEN) == MAGIC_LEN
                      && memcmp(magic, MAGIC, MAGIC_LEN) == 0);
        close(fd);
        if (!is_enc) continue;

        snprintf(jobs[*njobs].path, sizeof(jobs[0].path), "%s", path);
        snprintf(jobs[*njobs].name, sizeof(jobs[0].name), "%s", de->d_name);
        jobs[*njobs].fd = -1;
        (*njobs)++;
    }
    closedir(dp);
}

/* Scan directory, decrypt all encrypted libs in parallel using pthreads */
static int scan_encrypted_libs(const char *exe_path, const uint8_t *key,
                               int *lib_fds, char (*lib_names)[MAX_NAME + 1],
                               int *nlibs)
{
    char dir[4096];
    const char *slash = strrchr(exe_path, '/');
    if (slash) {
        size_t dlen = (size_t)(slash - exe_path);
        if (dlen >= sizeof(dir)) return -1;
        memcpy(dir, exe_path, dlen);
        dir[dlen] = '\0';
    } else {
        dir[0] = '.'; dir[1] = '\0';
    }

    /* Phase 1: collect encrypted file paths */
    dec_job_t *jobs = calloc(MAX_FILES, sizeof(dec_job_t));
    if (!jobs) return -1;
    int njobs = 0;
    collect_enc_paths(dir, jobs, &njobs, MAX_FILES);

    if (njobs == 0) { free(jobs); return 0; }

    /* Phase 2: decrypt in parallel */
    long ncpus = sysconf(_SC_NPROCESSORS_ONLN);
    if (ncpus < 1) ncpus = 4;
    int nthreads = (njobs < (int)ncpus) ? njobs : (int)ncpus;

    for (int i = 0; i < njobs; i++)
        jobs[i].key = key;

    dec_pool_t pool = { .jobs = jobs, .njobs = njobs, .next = 0 };
    pthread_t *tids = calloc((size_t)nthreads, sizeof(pthread_t));
    if (!tids) { free(jobs); return -1; }

    for (int t = 0; t < nthreads; t++)
        pthread_create(&tids[t], NULL, pool_worker, &pool);
    for (int t = 0; t < nthreads; t++)
        pthread_join(tids[t], NULL);

    /* Phase 3: collect results */
    for (int i = 0; i < njobs && *nlibs < MAX_FILES; i++) {
        if (jobs[i].fd >= 0) {
            lib_fds[*nlibs] = jobs[i].fd;
            memcpy(lib_names[*nlibs], jobs[i].name, MAX_NAME + 1);
            (*nlibs)++;
            fprintf(stderr, "[antirev] decrypted: %s\n", jobs[i].name);
        }
    }

    free(tids);
    free(jobs);
    return 0;
}

/* ------------------------------------------------------------------ */
/*  Shared: raise the process fd limit to its hard cap                  */
/* ------------------------------------------------------------------ */

/* The daemon holds ~nlibs memfds + a listen socket; protected exes
 * similarly receive ~nlibs fds via SCM_RIGHTS during Phase 3.  Both
 * routinely outgrow the default 1024 soft limit. */
static void raise_fd_limit(void) {
    struct rlimit rl;
    if (getrlimit(RLIMIT_NOFILE, &rl) == 0 && rl.rlim_cur < rl.rlim_max) {
        rl.rlim_cur = rl.rlim_max;
        setrlimit(RLIMIT_NOFILE, &rl);
    }
}

/* ------------------------------------------------------------------ */
/*  Phase 3 helpers: fetch encrypted lib fds from the libd daemon       */
/* ------------------------------------------------------------------ */

/* Write "<dir>/.antirev-libd[-arch]" to `out`, falling back to the
 * arch-free name if the suffixed binary isn't present. */
static void derive_daemon_path(const char *real_exe, char *out, size_t out_sz) {
    const char *slash = strrchr(real_exe, '/');
    size_t dirlen = slash ? (size_t) (slash - real_exe) : 1;
    if (!slash) {
        out[0] = '.';
        dirlen = 1;
    } else {
        memcpy(out, real_exe, dirlen);
    }
#if defined(__x86_64__) || defined(__i386__)
    snprintf(out + dirlen, out_sz - dirlen, "/.antirev-libd-x86_64");
#elif defined(__aarch64__)
    snprintf(out + dirlen, out_sz - dirlen, "/.antirev-libd-aarch64");
#else
    snprintf(out + dirlen, out_sz - dirlen, "/.antirev-libd");
#endif
    if (access(out, X_OK) != 0)
        snprintf(out + dirlen, out_sz - dirlen, "/.antirev-libd");
}

/* Fork the daemon binary if it's on disk; parent waits for the daemon
 * to self-daemonize (it _exit(0)s the launching process).  Returns 1
 * if launched, 0 otherwise.
 *
 * The launching parent's exit status reflects whether the daemon got
 * far enough to fork its serving child.  127 = execve failure.  1 =
 * daemon setup error (e.g. bind() collision when an impostor squats
 * our abstract socket name).  Anything non-zero means no serving
 * daemon is up; returning 0 lets fetch_libs_from_daemon retry-then-
 * fail rather than spin against a dead spawn for 50 attempts. */
static int spawn_local_daemon(const char *real_exe, char *const *envp) {
    char path[4096];
    derive_daemon_path(real_exe, path, sizeof(path));
    if (access(path, X_OK) != 0)
        return 0;

    pid_t pid = fork();
    if (pid == 0) {
        char *dargv[] = {path, NULL};
        execve(path, dargv, envp);
        _exit(127);
    }
    if (pid < 0)
        return 0;
    int st;
    if (waitpid(pid, &st, 0) < 0)
        return 0;
    if (!WIFEXITED(st) || WEXITSTATUS(st) != 0) {
        fprintf(stderr, "[antirev] daemon launch failed (exit=%d signal=%d)\n",
                WIFEXITED(st) ? WEXITSTATUS(st) : -1,
                WIFSIGNALED(st) ? WTERMSIG(st) : 0);
        return 0;
    }
    return 1;
}

/* Compute DT_NEEDED ∩ encrypted — what we need to eagerly fetch.  The
 * exe's DT_NEEDED list is a mix of encrypted (daemon-managed) and
 * unencrypted (resolved by ld.so normally) libs; only the former
 * should make a round trip. */
static int intersect_needed_encrypted(const char (*needed)[MAX_NAME + 1], int n_needed, const char (*enc)[MAX_NAME + 1],
                                      int n_enc, char (*out)[MAX_NAME + 1]) {
    int n_out = 0;
    for (int k = 0; k < n_needed; k++) {
        for (int j = 0; j < n_enc; j++) {
            if (strcmp(needed[k], enc[j]) == 0) {
                memcpy(out[n_out++], needed[k], MAX_NAME + 1);
                break;
            }
        }
    }
    return n_out;
}

/* Try one connect+fetch attempt.  Returns 0 on success (populates out
 * params), -1 on protocol failure (socket already closed), -2 on
 * connect failure (retry).  daemon_sd output is the kept-open socket
 * in needed-section mode, or -1 if the socket was closed after fetch. */
static int daemon_connect_and_fetch(const struct sockaddr_un *addr, socklen_t addr_len, int has_needed_section,
                                    int n_needed, const char (*needed_names)[MAX_NAME + 1], int *lib_fds,
                                    char (*lib_names)[MAX_NAME + 1], int *nlibs, char (*all_enc_names)[MAX_NAME + 1],
                                    int *n_all_enc, int *daemon_sd) {
    int sd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (sd < 0)
        return -2;
    if (connect(sd, (struct sockaddr *) addr, addr_len) != 0) {
        close(sd);
        return -2;
    }

    /* Verify the daemon is owned by our uid before exchanging any
     * data.  The abstract socket name is derived from a hash of the
     * AES key, which is plaintext in the daemon binary's trailer —
     * any uid that can read the binary can compute the name and
     * pre-bind it to MitM us.  The daemon already verifies clients
     * via SO_PEERCRED on accept; this is the symmetric check on
     * connect.  Return -1 (terminal) so the retry loop doesn't spin:
     * if the wrong uid is squatting the name, our spawn_local_daemon
     * can't bind it either, and retrying just delays the failure. */
    struct ucred cred;
    socklen_t clen = sizeof(cred);
    if (getsockopt(sd, SOL_SOCKET, SO_PEERCRED, &cred, &clen) < 0
        || cred.uid != getuid()) {
        fprintf(stderr,
                "[antirev] daemon impostor detected (peer uid %u, expected %u)\n",
                (unsigned)cred.uid, (unsigned)getuid());
        close(sd);
        return -1;
    }

    /* Step 1: full name list, no fds. */
    if (daemon_request_names(sd, all_enc_names, n_all_enc) < 0 || *n_all_enc == 0) {
        close(sd);
        return -1;
    }

    if (has_needed_section) {
        char enc_needed[MAX_FILES][MAX_NAME + 1];
        int n_enc_needed = intersect_needed_encrypted(needed_names, n_needed, all_enc_names, *n_all_enc, enc_needed);
        if (n_enc_needed > 0) {
            if (daemon_request_libs(sd, enc_needed, n_enc_needed, lib_fds, lib_names, nlibs) < 0 || *nlibs == 0) {
                close(sd);
                return -1;
            }
        } else {
            /* No encrypted DT_NEEDED — dlopen_shim handles everything lazily. */
            *nlibs = 0;
        }
        /* Keep socket open for lazy OP_GET_CLOSURE requests. */
        *daemon_sd = sd;
    } else {
        /* Legacy bundle: fetch everything eagerly, drop the socket. */
        if (daemon_request_libs(sd, NULL, 0, lib_fds, lib_names, nlibs) < 0 || *nlibs == 0) {
            close(sd);
            return -1;
        }
        daemon_send_bye(sd);
        close(sd);
        *n_all_enc = 0; /* no lazy mode */
    }
    return 0;
}

/* Connect to the lib daemon (launching it if missing), negotiate the
 * encrypted lib set, and fetch the DT_NEEDED fds eagerly.  Keeps the
 * socket open in lazy mode so dlopen_shim can request closures on
 * demand.  Returns 0 on success, -1 on terminal failure. */
static int fetch_libs_from_daemon(const char *real_exe, char *const *envp, const uint8_t *key, int has_needed_section,
                                  int n_needed, const char (*needed_names)[MAX_NAME + 1], int *lib_fds,
                                  char (*lib_names)[MAX_NAME + 1], int *nlibs, char (*all_enc_names)[MAX_NAME + 1],
                                  int *n_all_enc, int *daemon_sd) {
    raise_fd_limit(); /* ~nlibs fds will arrive via SCM_RIGHTS */

    struct sockaddr_un addr;
    socklen_t addr_len = make_sock_addr(&addr, key);

    int daemon_launched = 0;
    for (int retry = 0; retry < 50; retry++) {
        int rc = daemon_connect_and_fetch(&addr, addr_len, has_needed_section, n_needed, needed_names, lib_fds,
                                          lib_names, nlibs, all_enc_names, n_all_enc, daemon_sd);
        if (rc == 0) {
            fprintf(stderr,
                    "[antirev] daemon: %d enc libs total, "
                    "%d eagerly fetched (DT_NEEDED)\n",
                    *n_all_enc, *nlibs);
            return 0;
        }
        if (rc == -1)
            break; /* protocol failure — no point retrying */

        if (!daemon_launched && retry == 0)
            daemon_launched = spawn_local_daemon(real_exe, envp);

        usleep(100000);
    }
    fprintf(stderr, "[antirev] failed to connect to lib daemon\n");
    return -1;
}

/* ------------------------------------------------------------------ */
/*  Phase 5 helpers: build the envp we hand the protected process        */
/* ------------------------------------------------------------------ */

/* All the per-launch state Phase 5 needs from main().  Bundled to
 * keep build_exec_env()'s signature manageable — the 17 fields were
 * previously 17 locals in main(). */
typedef struct {
    char *const *envp;
    const char *real_exe;
    int main_fd;
    int antirev_shim_fd;
    int has_needed_section;
    int nlibs;
    int n_dt_needed;
    int *dt_needed_fds;
    int n_fdmap;
    const char (*fdmap_names)[MAX_NAME + 1];
    int *fdmap_fds;
    int daemon_sd;
    int n_all_enc;
    const char (*all_enc_names)[MAX_NAME + 1];
    const char *link_dir_ptr; /* NULL if no symlink dir was created */
    const char *link_dir;
} exec_env_cfg_t;

/* Copy the caller's LD_PRELOAD with antirev /proc/self/fd/ entries
 * stripped — those come from a parent protected process and would
 * cause a cascading double-load of the shims. */
static void filter_inherited_ld_preload(char *const *envp, int envc, char *buf, size_t buf_sz) {
    buf[0] = '\0';
    for (int j = 0; j < envc; j++) {
        if (strncmp(envp[j], "LD_PRELOAD=", 11) != 0)
            continue;
        const char *src = envp[j] + 11;
        size_t off = 0;
        while (*src) {
            const char *end = src;
            while (*end && *end != ':')
                end++;
            size_t tlen = (size_t) (end - src);
            if (tlen > 0 && strncmp(src, "/proc/self/fd/", 14) != 0) {
                if (off > 0 && off + 1 < buf_sz)
                    buf[off++] = ':';
                if (off + tlen < buf_sz) {
                    memcpy(buf + off, src, tlen);
                    off += tlen;
                }
            }
            src = (*end == ':') ? end + 1 : end;
        }
        buf[off] = '\0';
        return;
    }
}

/* Look up an existing env var's value in the envp array, returning
 * the pointer past the "NAME=" prefix, or NULL if not found. */
static const char *find_env_value(char *const *envp, int envc, const char *name_eq, size_t name_eq_len) {
    for (int j = 0; j < envc; j++) {
        if (strncmp(envp[j], name_eq, name_eq_len) == 0)
            return envp[j] + name_eq_len;
    }
    return NULL;
}

/* "LD_LIBRARY_PATH=<link_dir>[:<existing>]", heap-allocated. */
static char *build_ld_library_path(char *const *envp, int envc, const char *link_dir) {
    const char *existing = find_env_value(envp, envc, "LD_LIBRARY_PATH=", 16);
    size_t need = 17 + strlen(link_dir) + (existing ? 1 + strlen(existing) : 0);
    char *out = malloc(need);
    if (!out)
        return NULL;
    if (existing && *existing)
        snprintf(out, need, "LD_LIBRARY_PATH=%s:%s", link_dir, existing);
    else
        snprintf(out, need, "LD_LIBRARY_PATH=%s", link_dir);
    return out;
}

/* True if `exe_basename` needs ANTIREV_NO_PRELOAD=1 — add names here
 * for exes whose dlopen'd libs have implicit inter-lib symbol deps
 * that break when constructors run in per-dep isolation. */
static int exe_is_no_preload_blacklisted(const char *exe_basename) {
    static const char *blacklist[] = {"GUI", NULL};
    for (int k = 0; blacklist[k]; k++)
        if (strcmp(exe_basename, blacklist[k]) == 0)
            return 1;
    return 0;
}

/* "LD_PRELOAD=/proc/self/fd/A[:<dt_needed_fds>][:<existing>]"
 *
 * antirev_shim is the single shim DSO (combined exe-identity, dlopen,
 * and on aarch64 ANTI_LoadProcess + popen interceptors).  The
 * DT_NEEDED run is only emitted in backward-compat mode (no needed
 * section): legacy packages don't carry a DT_NEEDED list so we fall
 * back to putting every encrypted lib on LD_PRELOAD. */
static char *build_ld_preload(int antirev_shim_fd, int compat_preload, int n_dt_needed,
                              const int *dt_needed_fds, const char *existing_preload) {
    size_t need = 128 + (compat_preload ? (size_t) n_dt_needed * 24 : 0) +
                  (existing_preload ? 1 + strlen(existing_preload) : 0);
    char *out = malloc(need);
    if (!out)
        return NULL;
    int off = snprintf(out, need, "LD_PRELOAD=/proc/self/fd/%d", antirev_shim_fd);
    if (compat_preload) {
        for (int j = 0; j < n_dt_needed; j++)
            off += snprintf(out + off, need - (size_t) off, ":/proc/self/fd/%d", dt_needed_fds[j]);
    }
    if (existing_preload)
        snprintf(out + off, need - (size_t) off, ":%s", existing_preload);
    return out;
}

/* "ANTIREV_FD_MAP=name1=fd1,name2=fd2,…" for dlopen'd libs. */
static char *build_antirev_fd_map(int n_fdmap, const char (*fdmap_names)[MAX_NAME + 1], const int *fdmap_fds) {
    size_t need = 16 + (size_t) n_fdmap * (MAX_NAME + 16);
    char *out = malloc(need);
    if (!out)
        return NULL;
    int off = snprintf(out, need, "ANTIREV_FD_MAP=");
    for (int j = 0; j < n_fdmap; j++) {
        if (j > 0)
            out[off++] = ',';
        off += snprintf(out + off, need - (size_t) off, "%s=%d", fdmap_names[j], fdmap_fds[j]);
    }
    return out;
}

/* "ANTIREV_ENC_LIBS=name1,name2,…" — the full encrypted-lib set the
 * daemon manages.  dlopen_shim checks incoming dlopen basenames
 * against this set before opening the socket. */
static char *build_enc_libs(int n_all_enc, const char (*all_enc_names)[MAX_NAME + 1]) {
    size_t need = 20 + (size_t) n_all_enc * (MAX_NAME + 2);
    char *out = malloc(need);
    if (!out)
        return NULL;
    int off = snprintf(out, need, "ANTIREV_ENC_LIBS=");
    for (int j = 0; j < n_all_enc; j++) {
        if (j > 0)
            out[off++] = ',';
        off += snprintf(out + off, need - (size_t) off, "%s", all_enc_names[j]);
    }
    return out;
}

/* Build the three lazy-mode env strings into out-params.  `symlink_dir`
 * is only produced when a symlink dir was set up; the other two are
 * always produced in lazy mode. */
static void build_lazy_env(int daemon_sd, const char *link_dir_ptr, const char *link_dir, int n_all_enc,
                           const char (*all_enc_names)[MAX_NAME + 1], char **out_sock, char **out_sym, char **out_enc) {
    *out_sock = malloc(48);
    if (*out_sock)
        snprintf(*out_sock, 48, "ANTIREV_LIBD_SOCK=%d", daemon_sd);

    if (link_dir_ptr) {
        *out_sym = malloc(64);
        if (*out_sym)
            snprintf(*out_sym, 64, "ANTIREV_SYMLINK_DIR=%s", link_dir);
    } else {
        *out_sym = NULL;
    }

    *out_enc = build_enc_libs(n_all_enc, all_enc_names);
}

/* "ANTIREV_CLOSE_FDS=fd1,fd2,…" — exe_shim closes these in its ctor.
 * By that point glibc has already mmap'd every DT_NEEDED lib so the
 * fds are pure bookkeeping; freeing the slots helps select() callers
 * (FD_SETSIZE=1024). */
static char *build_close_fds(int n_dt_needed, const int *dt_needed_fds) {
    size_t need = 20 + (size_t) n_dt_needed * 12;
    char *out = malloc(need);
    if (!out)
        return NULL;
    int off = snprintf(out, need, "ANTIREV_CLOSE_FDS=");
    for (int j = 0; j < n_dt_needed; j++) {
        if (j > 0)
            out[off++] = ',';
        off += snprintf(out + off, need - (size_t) off, "%d", dt_needed_fds[j]);
    }
    return out;
}

/* True for env entries we're about to rewrite — skipped when copying
 * the inherited env forward. */
static int env_is_antirev_managed(const char *e) {
    static const char *const prefixes[] = {
            "LD_PRELOAD=",
            "LD_LIBRARY_PATH=",
            "ANTIREV_REAL_EXE=",
            "ANTIREV_MAIN_FD=",
            "ANTIREV_FD_MAP=",
            "ANTIREV_CLOSE_FDS=",
            "ANTIREV_LIBD_SOCK=",
            "ANTIREV_ENC_LIBS=",
            "ANTIREV_SYMLINK_DIR=",
            "ANTIREV_NO_PRELOAD=",
            NULL,
    };
    for (int i = 0; prefixes[i]; i++)
        if (strncmp(e, prefixes[i], strlen(prefixes[i])) == 0)
            return 1;
    return 0;
}

/* Build the full env array for fexecve.  Returns a malloc'd
 * NULL-terminated vector where the individual entries are a mix of
 * caller-owned (inherited) and build_*-allocated strings — no attempt
 * is made to track ownership since fexecve will replace the address
 * space anyway. */
static char **build_exec_env(const exec_env_cfg_t *cfg) {
    int envc = 0;
    while (cfg->envp[envc])
        envc++;

    char filtered[8192];
    filter_inherited_ld_preload(cfg->envp, envc, filtered, sizeof(filtered));
    const char *existing_preload = filtered[0] ? filtered : NULL;

    char *ld_libpath = cfg->link_dir_ptr ? build_ld_library_path(cfg->envp, envc, cfg->link_dir) : NULL;

    const char *base = strrchr(cfg->real_exe, '/');
    base = base ? base + 1 : cfg->real_exe;
    int force_no_preload = exe_is_no_preload_blacklisted(base);

    /* +12 extras: REAL_EXE, MAIN_FD, LD_PRELOAD, FD_MAP, LIBPATH,
     * CLOSE_FDS, LIBD_SOCK, ENC_LIBS, SYMLINK_DIR, NO_PRELOAD, NULL + spare */
    char **out = malloc((size_t) (envc + 12) * sizeof(char *));
    if (!out)
        return NULL;

    char *real_exe_entry = malloc(4096 + 32);
    char *main_fd_entry = malloc(32);
    if (!real_exe_entry || !main_fd_entry) {
        free(out);
        return NULL;
    }
    snprintf(real_exe_entry, 4096 + 32, "ANTIREV_REAL_EXE=%s", cfg->real_exe);
    snprintf(main_fd_entry, 32, "ANTIREV_MAIN_FD=%d", cfg->main_fd);

    int compat_preload = !cfg->has_needed_section && cfg->nlibs > 0;
    char *ld_preload_entry = build_ld_preload(cfg->antirev_shim_fd, compat_preload,
                                              cfg->n_dt_needed, cfg->dt_needed_fds, existing_preload);
    if (!ld_preload_entry) {
        free(out);
        return NULL;
    }

    char *fd_map_entry = cfg->n_fdmap > 0 ? build_antirev_fd_map(cfg->n_fdmap, cfg->fdmap_names, cfg->fdmap_fds) : NULL;

    char *libd_sock = NULL, *symlink_dir = NULL, *enc_libs = NULL;
    int lazy_mode = (cfg->daemon_sd >= 0 && cfg->n_all_enc > 0);
    if (lazy_mode)
        build_lazy_env(cfg->daemon_sd, cfg->link_dir_ptr, cfg->link_dir, cfg->n_all_enc, cfg->all_enc_names, &libd_sock,
                       &symlink_dir, &enc_libs);

    /* Always emit ANTIREV_SYMLINK_DIR when we have a dir, not just in
     * lazy mode — exe_shim's atexit handler reads it to remove the
     * dir on normal process exit. */
    if (!symlink_dir && cfg->link_dir_ptr) {
        symlink_dir = malloc(64);
        if (symlink_dir)
            snprintf(symlink_dir, 64, "ANTIREV_SYMLINK_DIR=%s", cfg->link_dir);
    }

    char *close_fds = (cfg->has_needed_section && cfg->n_dt_needed > 0)
                              ? build_close_fds(cfg->n_dt_needed, cfg->dt_needed_fds)
                              : NULL;

    int ei = 0;
    for (int j = 0; j < envc; j++) {
        if (env_is_antirev_managed(cfg->envp[j]))
            continue;
        out[ei++] = cfg->envp[j];
    }
    out[ei++] = real_exe_entry;
    out[ei++] = main_fd_entry;
    out[ei++] = ld_preload_entry;
    if (fd_map_entry)
        out[ei++] = fd_map_entry;
    if (ld_libpath)
        out[ei++] = ld_libpath;
    if (close_fds)
        out[ei++] = close_fds;
    if (libd_sock)
        out[ei++] = libd_sock;
    if (enc_libs)
        out[ei++] = enc_libs;
    if (symlink_dir)
        out[ei++] = symlink_dir;
    if (force_no_preload)
        out[ei++] = "ANTIREV_NO_PRELOAD=1";
    out[ei] = NULL;
    return out;
}

/* ------------------------------------------------------------------ */
/*  Mode A: lightweight lib daemon                                      */
/* ------------------------------------------------------------------ */

/* Reap stale /tmp/antirev_<pid>_XXXXXX dirs whose owner PID is dead.
 *
 * Each protected exe creates one of these on launch as its symlink
 * dir (Phase 4c).  exe_shim's atexit handler removes it on normal
 * exit; this sweep handles the SIGKILL / segfault / hard-crash case
 * that atexit can't.  The PID tag encodes ownership so we can decide
 * safely without coordinating with active exes.
 *
 * Called twice in the daemon's lifecycle: once at startup (catches
 * anything from prior crashed runs) and once on shutdown (catches
 * any of our session's exes that crashed before atexit could fire).
 *
 * Safe under PID reuse: in the unlikely case a recycled PID matches
 * a stale dir name, the new PID has nothing to do with that dir, so
 * removing it harms nothing. */
static void sweep_dead_symlink_dirs(void) {
    DIR *dp = opendir("/tmp");
    if (!dp) return;

    struct dirent *de;
    while ((de = readdir(dp)) != NULL) {
        if (strncmp(de->d_name, "antirev_", 8) != 0) continue;

        /* Parse "antirev_<pid>_<rand>" — accept the legacy
         * "antirev_<rand>" form too by skipping it (no PID = can't
         * decide ownership safely). */
        const char *p = de->d_name + 8;
        char *endp;
        long pid = strtol(p, &endp, 10);
        if (endp == p || *endp != '_' || pid <= 0) continue;

        if (kill((pid_t)pid, 0) == 0 || errno != ESRCH)
            continue; /* owner still alive — leave it */

        char dir[128];
        snprintf(dir, sizeof(dir), "/tmp/%.120s", de->d_name);

        /* Walk + unlink the dir's contents (all symlinks).  Use a
         * second opendir rather than openat-style iteration to keep
         * this short.  rmdir at the end. */
        DIR *sub = opendir(dir);
        if (sub) {
            struct dirent *se;
            while ((se = readdir(sub)) != NULL) {
                if (strcmp(se->d_name, ".") == 0 || strcmp(se->d_name, "..") == 0)
                    continue;
                /* %.* widths bound each directive so fortify can prove
                 * no truncation — see dlopen_shim's preload helper. */
                char path[256];
                snprintf(path, sizeof(path), "%.127s/%.127s", dir, se->d_name);
                unlink(path);
            }
            closedir(sub);
        }
        if (rmdir(dir) == 0)
            fprintf(stderr, "[antirev] reaped stale symlink dir %s (pid %ld dead)\n",
                    dir, pid);
    }
    closedir(dp);
}

/* Scan /tmp/antirev-deps.log-style graph dump so it's reachable when
 * the daemon's stderr is closed (e.g., launched from sysmgr). */
static void dump_deps_graph_log(const char (*lib_names)[MAX_NAME + 1], int nlibs) {
    FILE *lf = fopen("/tmp/antirev-deps.log", "w");
    if (!lf)
        return;
    fprintf(lf, "# antirev deps graph (%d libs)\n", nlibs);
    for (int i = 0; i < nlibs; i++) {
        fprintf(lf, "%s %d", lib_names[i], g_deps_count[i]);
        for (int k = 0; k < g_deps_count[i]; k++)
            fprintf(lf, " %s", lib_names[g_deps_idx[i][k]]);
        fprintf(lf, "\n");
    }
    fclose(lf);
}

/* Open, bind, and listen on the abstract socket derived from `key`.
 * Returns the listen fd on success, -1 on failure. */
static int daemon_open_listen_socket(const uint8_t *key) {
    struct sockaddr_un addr;
    socklen_t addr_len = make_sock_addr(&addr, key);

    int sd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (sd < 0) {
        perror("socket");
        return -1;
    }
    if (bind(sd, (struct sockaddr *) &addr, addr_len) < 0) {
        perror("[antirev] daemon bind");
        close(sd);
        return -1;
    }
    listen(sd, 16);
    return sd;
}

/* Time `scan_encrypted_libs` and print the decrypt duration. */
static int decrypt_own_libs(const char *real_exe, const uint8_t *key, int *lib_fds, char (*lib_names)[MAX_NAME + 1],
                            int *nlibs) {
    struct timespec t_start, t_end;
    clock_gettime(CLOCK_MONOTONIC, &t_start);
    scan_encrypted_libs(real_exe, key, lib_fds, lib_names, nlibs);
    if (*nlibs == 0) {
        fprintf(stderr, "[antirev] no main binary and no libs found\n");
        return -1;
    }
    clock_gettime(CLOCK_MONOTONIC, &t_end);
    double elapsed = (double) (t_end.tv_sec - t_start.tv_sec) + (double) (t_end.tv_nsec - t_start.tv_nsec) / 1e9;
    fprintf(stderr, "[antirev] decrypted %d libs in %.1fs\n", *nlibs, elapsed);
    return 0;
}

/* Build the per-lib DT_NEEDED adjacency used by OP_GET_CLOSURE so the
 * daemon can return a lib plus its transitive encrypted deps in a
 * single round trip.  Prints a summary + dumps the graph for debug. */
static void build_and_log_deps_graph(int *lib_fds, const char (*lib_names)[MAX_NAME + 1], int nlibs) {
    build_deps_graph(lib_fds, lib_names, nlibs);
    int total_edges = 0, zero = 0;
    for (int i = 0; i < nlibs; i++) {
        total_edges += g_deps_count[i];
        if (g_deps_count[i] == 0)
            zero++;
    }
    fprintf(stderr,
            "[antirev] deps graph: %d libs, %d edges, "
            "%d libs with 0 deps\n",
            nlibs, total_edges, zero);
    dump_deps_graph_log(lib_names, nlibs);
}

/* Run as Mode A: decrypt own libs, build deps graph, daemonize, serve
 * lib fds with clean shutdown on SIGTERM/INT/HUP/QUIT.
 *
 * Daemon process layout (after the daemonising fork):
 *   - Main thread: blocks shutdown signals and sigwait()s; on signal
 *     it pokes the eventfd, joins the worker, closes resources, exits.
 *   - Worker thread: runs the epoll serve loop.  Wakes when the
 *     eventfd fires, returns from daemon_serve.
 *
 * Returns to the caller only on setup failure; on the success path
 * the main thread _exit(0)s after the worker is joined. */
static int run_daemon_forever(const char *real_exe, uint8_t *key, int *lib_fds, char (*lib_names)[MAX_NAME + 1],
                              int *nlibs) {
    raise_fd_limit();

    /* Startup sweep: reap any /tmp/antirev_<pid>_* dirs whose owner
     * is dead.  Catches dirs left behind by protected exes that
     * crashed before exe_shim's atexit could fire. */
    sweep_dead_symlink_dirs();

    if (decrypt_own_libs(real_exe, key, lib_fds, lib_names, nlibs) < 0)
        return 1;

    build_and_log_deps_graph(lib_fds, lib_names, *nlibs);

    int listen_sd = daemon_open_listen_socket(key);
    explicit_bzero(key, KEY_SIZE);
    if (listen_sd < 0)
        return 1;
    fprintf(stderr, "[antirev] lib daemon ready (%d libs)\n", *nlibs);

    pid_t pid = fork();
    if (pid < 0) {
        perror("fork");
        return 1;
    }
    if (pid > 0)
        _exit(0); /* parent: daemon is running */

    /* === child (long-lived daemon) === */
    setsid();
    close(STDIN_FILENO);
    close(STDOUT_FILENO);
    close(STDERR_FILENO);

    /* Process-wide before any thread spawns: ignore SIGPIPE (writes
     * to a closed client socket should EPIPE, not kill us) and
     * register the shutdown-signal mask so both the main thread
     * and the worker inherit it.  Doing this before pthread_create
     * eliminates the race where a fast-arriving SIGPIPE could
     * terminate the process between create and install. */
    signal(SIGPIPE, SIG_IGN);

    sigset_t shutdown_sigs;
    sigemptyset(&shutdown_sigs);
    sigaddset(&shutdown_sigs, SIGTERM);
    sigaddset(&shutdown_sigs, SIGINT);
    sigaddset(&shutdown_sigs, SIGHUP);
    sigaddset(&shutdown_sigs, SIGQUIT);
    if (pthread_sigmask(SIG_BLOCK, &shutdown_sigs, NULL) != 0)
        _exit(1);

    int shutdown_efd = eventfd(0, EFD_CLOEXEC);
    if (shutdown_efd < 0) {
        close(listen_sd);
        _exit(1);
    }

    struct daemon_serve_args args = {
        .listen_fd    = listen_sd,
        .shutdown_efd = shutdown_efd,
        .lib_fds      = lib_fds,
        .lib_names    = lib_names,
        .nlibs        = *nlibs,
    };

    pthread_t worker;
    if (pthread_create(&worker, NULL, daemon_serve_thread, &args) != 0) {
        close(shutdown_efd);
        close(listen_sd);
        _exit(1);
    }

    /* Park the main thread until a shutdown signal arrives. */
    int sig = 0;
    sigwait(&shutdown_sigs, &sig);

    /* Wake the worker.  An eventfd write of 8 bytes is atomic and
     * cannot partial-write; the worker doesn't read the payload, it
     * only needs the fd to become readable. */
    uint64_t one = 1;
    ssize_t  ew  = write(shutdown_efd, &one, sizeof(one));
    (void)ew;

    pthread_join(worker, NULL);

    /* Tear down everything that crossed the thread boundary. */
    close(listen_sd);
    close(shutdown_efd);
    for (int i = 0; i < *nlibs; i++)
        if (lib_fds[i] >= 0) close(lib_fds[i]);

    /* Shutdown sweep: catches any dirs whose owner exe crashed
     * during this daemon's session before its atexit could fire. */
    sweep_dead_symlink_dirs();

    _exit(0);
}

/* ------------------------------------------------------------------ */
/*  Phase 6 helpers: cross-arch exec via QEMU user-mode                 */
/* ------------------------------------------------------------------ */

/* Read the first 20 bytes of `fd` and return non-zero if its ELF
 * e_machine differs from the host arch — i.e. we need QEMU to run it. */
static int needs_qemu_for_fd(int fd) {
    uint8_t hdr[20];
    if (pread(fd, hdr, sizeof(hdr), 0) != sizeof(hdr))
        return 0;
    if (hdr[0] != 0x7f || hdr[1] != 'E' || hdr[2] != 'L' || hdr[3] != 'F')
        return 0;
    uint16_t e_machine = hdr[18] | ((uint16_t) hdr[19] << 8);
#if defined(__x86_64__) || defined(__i386__)
    return e_machine != 0x3E && e_machine != 0x03; /* not x86_64/x86 */
#elif defined(__aarch64__)
    return e_machine != 0xB7; /* not aarch64 */
#else
    (void) e_machine;
    return 0;
#endif
}

/* Build argv for a QEMU exec: [binname, /proc/self/fd/N, <original argv[1..]>, NULL].
 * Caller owns the returned allocation. */
static char **build_qemu_argv(const char *binname, const char *fd_path, char *const *argv, int orig_argc) {
    char **out = malloc((size_t) (orig_argc + 2) * sizeof(char *));
    if (!out)
        return NULL;
    out[0] = (char *) binname;
    out[1] = (char *) fd_path;
    for (int i = 1; i < orig_argc; i++)
        out[i + 1] = argv[i];
    out[orig_argc + 1] = NULL;
    return out;
}

/* Try each well-known QEMU path in order; execve on the first hit.
 * Returns only on failure (execve on success never returns). */
static void try_exec_known_qemu(char **qemu_argv, char **new_env) {
    static const char *qemu_candidates[] = {"/tmp/.antirev-qemu-aarch64", "/usr/bin/qemu-aarch64-static",
                                            "/usr/bin/qemu-aarch64", NULL};
    for (int qi = 0; qemu_candidates[qi]; qi++) {
        struct stat st;
        if (stat(qemu_candidates[qi], &st) == 0)
            execve(qemu_candidates[qi], qemu_argv, new_env);
    }
}

/* Buffered copy of an fd.  Returns 0 on success, -1 on any write error. */
static int copy_fd_to_fd(int src, int dst) {
    char buf[8192];
    ssize_t n;
    while ((n = read(src, buf, sizeof(buf))) > 0) {
        ssize_t off = 0;
        while (off < n) {
            ssize_t w = write(dst, buf + off, (size_t) (n - off));
            if (w <= 0)
                return -1;
            off += w;
        }
    }
    return n < 0 ? -1 : 0;
}

/* Probe /proc/<pid>/exe for up to `timeout_ms` (polled at 20ms) looking
 * for a path containing "qemu".  Returns the resolved path in `out` on
 * success (NUL-terminated), or returns -1 on timeout. */
static int wait_for_qemu_exe(pid_t pid, char *out, size_t out_sz, int timeout_ms) {
    char proc_exe[64];
    snprintf(proc_exe, sizeof(proc_exe), "/proc/%d/exe", (int) pid);
    for (int i = 0; i < timeout_ms / 20; i++) {
        usleep(20000);
        ssize_t n = readlink(proc_exe, out, out_sz - 1);
        if (n > 0) {
            out[n] = '\0';
            if (strstr(out, "qemu"))
                return 0;
        }
    }
    return -1;
}

/* Probe-cache path: fork a child through binfmt_misc, copy its
 * /proc/<pid>/exe (= the QEMU binary the kernel chose) to /tmp so
 * we can exec it directly next time.  Handles Docker where QEMU
 * isn't on PATH (binfmt_misc F-flag keeps it kernel-side only).
 *
 * Returns 0 if the cache file is populated; -1 otherwise. */
static int cache_qemu_from_probe(int main_fd, char *const *argv, char **new_env) {
    pid_t probe = fork();
    if (probe == 0) {
        fexecve(main_fd, argv, new_env);
        _exit(127);
    }
    if (probe < 0)
        return -1;

    char qemu_path[256];
    int found = wait_for_qemu_exe(probe, qemu_path, sizeof(qemu_path), 1000);
    int cached = -1;
    if (found == 0) {
        char proc_exe[64];
        snprintf(proc_exe, sizeof(proc_exe), "/proc/%d/exe", (int) probe);
        int src = open(proc_exe, O_RDONLY);
        if (src >= 0) {
            int dst = open("/tmp/.antirev-qemu-aarch64", O_WRONLY | O_CREAT | O_TRUNC, 0755);
            if (dst >= 0) {
                if (copy_fd_to_fd(src, dst) == 0)
                    cached = 0;
                close(dst);
            }
            close(src);
        }
    }

    kill(probe, SIGKILL);
    int st;
    waitpid(probe, &st, 0);
    return cached;
}

/* Phase 6 dispatcher.  On native execution: fexecve(main_fd).  On
 * cross-arch: try cached QEMU, then known system paths, then fall
 * back to binfmt_misc-probe-and-cache, then re-exec through the
 * cached QEMU.  Any failure falls through to a direct fexecve — the
 * kernel's own binfmt handling is the last line of defence. */
static void exec_target(int main_fd, char *const *argv, char **new_env, const char *real_exe) {
    if (!needs_qemu_for_fd(main_fd)) {
        fexecve(main_fd, (char *const *) argv, new_env);
        return;
    }

    const char *binname = strrchr(real_exe, '/');
    binname = binname ? binname + 1 : real_exe;

    int orig_argc = 0;
    while (argv[orig_argc])
        orig_argc++;

    char fd_path[32];
    snprintf(fd_path, sizeof(fd_path), "/proc/self/fd/%d", main_fd);

    char **qemu_argv = build_qemu_argv(binname, fd_path, argv, orig_argc);
    if (qemu_argv) {
        try_exec_known_qemu(qemu_argv, new_env);
        free(qemu_argv);
    }

    if (cache_qemu_from_probe(main_fd, argv, new_env) == 0) {
        char **re_argv = build_qemu_argv(binname, fd_path, argv, orig_argc);
        if (re_argv) {
            execve("/tmp/.antirev-qemu-aarch64", re_argv, new_env);
            free(re_argv);
        }
    }

    fexecve(main_fd, (char *const *) argv, new_env);
}

/* ------------------------------------------------------------------ */
/*  main                                                               */
/* ------------------------------------------------------------------ */
int main(int argc __attribute__((unused)), char *argv[], char *envp[])
{
    /* 1. Capture real exe path before fexecve replaces /proc/self/exe.
     *    Use raw syscall to bypass any inherited LD_PRELOAD exe_shim from
     *    a parent protected binary — we need the true kernel-level path. */
    char real_exe[4096];
    {
        ssize_t n = (ssize_t)syscall(SYS_readlinkat, AT_FDCWD,
                                     "/proc/self/exe", real_exe, sizeof(real_exe) - 1);
        if (n <= 0) { perror("readlink /proc/self/exe"); return 1; }
        real_exe[n] = '\0';
    }

    /* 2. Open /proc/self/exe and read the 48-byte trailer */
    int self = open("/proc/self/exe", O_RDONLY);
    if (self < 0) { perror("open /proc/self/exe"); return 1; }

    off_t fsize = lseek(self, 0, SEEK_END);
    if (fsize < 48) {
        fprintf(stderr, "[antirev] binary too small\n");
        return 1;
    }

    /* Trailer layout: [bundle_offset:8B][key:32B][magic:8B] = 48 bytes */
    uint8_t trailer[48];
    if (pread(self, trailer, 48, fsize - 48) != 48) {
        perror("pread trailer"); return 1;
    }
    if (memcmp(trailer + 40, MAGIC, MAGIC_LEN) != 0) {
        fprintf(stderr, "[antirev] not a protected binary (magic not found)\n");
        return 1;
    }

    uint64_t bundle_off = u64le(trailer);

    /* 2. Extract key from trailer */
    uint8_t key[KEY_SIZE];
    memcpy(key, trailer + 8, KEY_SIZE);

    /* ----------------------------------------------------------------
     * Phase 1: scan bundle headers — collect metadata for every file.
     * We only read the tiny per-file headers; ciphertext is skipped via
     * offset arithmetic and never loaded into user-space memory here.
     * ---------------------------------------------------------------- */
    uint8_t tmp[2 + MAX_NAME + 1 + IV_SIZE + TAG_SIZE + 8]; /* max header */

    /* Read bundle_flags (1 byte) */
    if (pread(self, tmp, 1, (off_t) bundle_off) != 1) {
        perror("pread bundle_flags");
        return 1;
    }
    uint8_t bundle_flags = tmp[0];

    file_entry_t main_entry;
    int have_main = (bundle_flags & BFLAG_HAS_MAIN) != 0;
    off_t scan = (off_t) bundle_off + 1;

    if (have_main) {
        file_entry_t *e = &main_entry;

        /* name_len (2 bytes) */
        if (pread(self, tmp, 2, scan) != 2) { perror("pread name_len"); return 1; }
        uint16_t nlen = u16le(tmp);
        if (nlen > MAX_NAME) {
            fprintf(stderr, "[antirev] name too long in bundle\n");
            return 1;
        }
        scan += 2;

        /* name + iv + tag + ct_size */
        ssize_t hdr_rest = nlen + IV_SIZE + TAG_SIZE + 8;
        if (pread(self, tmp, (size_t)hdr_rest, scan) != hdr_rest) {
            perror("pread file header"); return 1;
        }
        memcpy(e->name, tmp, nlen);
        e->name[nlen]  = '\0';
        memcpy(e->iv, tmp + nlen, IV_SIZE);
        memcpy(e->tag, tmp + nlen + IV_SIZE, TAG_SIZE);
        e->ct_size = u64le(tmp + nlen + IV_SIZE + TAG_SIZE);
        scan          += hdr_rest;

        e->ct_offset   = (uint64_t)scan;
        scan          += (off_t)e->ct_size;

        /* Sanity: ciphertext must not overlap the trailer */
        if (e->ct_offset + e->ct_size > (uint64_t)(fsize - 48)) {
            fprintf(stderr, "[antirev] bundle extends past trailer\n");
            return 1;
        }
    }

    /* Parse needed-libs section (after file entries, when BFLAG_DAEMON_LIBS).
     * Format: [num_needed:2B] [name_len:2B name:...]... */
    int n_needed = 0;
    int has_needed_section = 0;
    char needed_names[MAX_FILES][MAX_NAME + 1];

    if (bundle_flags & BFLAG_DAEMON_LIBS) {
        has_needed_section = 1;
        uint8_t nbuf[2];
        if (pread(self, nbuf, 2, scan) == 2) {
            uint16_t nn = u16le(nbuf);
            scan += 2;
            for (int i = 0; i < (int)nn && i < MAX_FILES; i++) {
                if (pread(self, nbuf, 2, scan) != 2) break;
                uint16_t nl = u16le(nbuf);
                scan += 2;
                if (nl > MAX_NAME) break;
                if (pread(self, needed_names[n_needed], nl, scan) != nl) break;
                needed_names[n_needed][nl] = '\0';
                n_needed++;
                scan += nl;
            }
        }
    }

    /* ----------------------------------------------------------------
     * Phase 2: for each file, single-pass GHASH + CTR decryption.
     * Reads ciphertext once, writes plaintext to memfd, then verifies
     * the authentication tag.  On auth failure, plaintext is wiped.
     *
     * Peak user-space heap: one CHUNK_SIZE buffer.
     * ---------------------------------------------------------------- */
    uint8_t *chunk = malloc(CHUNK_SIZE);
    if (!chunk) { perror("malloc chunk"); return 1; }

    int main_fd = -1;
    int lib_fds[MAX_FILES];
    char lib_names[MAX_FILES][MAX_NAME + 1];
    int nlibs = 0;

    if (have_main) {
        file_entry_t *e = &main_entry;
        aes256gcm_ctx ctx;

        /* Single pass: GHASH + CTR simultaneously (halves I/O) */
        int fd = make_memfd(e->name);
        if (fd < 0) return 1;

        aes256gcm_init(&ctx, key, e->iv);
        uint64_t remaining = e->ct_size;
        off_t    pos       = (off_t)e->ct_offset;
        while (remaining > 0) {
            size_t  to_read = (remaining < CHUNK_SIZE) ? (size_t)remaining : CHUNK_SIZE;
            ssize_t got     = pread(self, chunk, to_read, pos);
            if (got != (ssize_t)to_read) { perror("pread ciphertext"); return 1; }
            aes256gcm_onepass(&ctx, chunk, chunk, to_read);
            if (write_chunk(fd, chunk, to_read) != 0) return 1;
            pos       += (off_t)to_read;
            remaining -= to_read;
        }
        if (aes256gcm_ghash_verify(&ctx, e->tag) != 0) {
            fprintf(stderr, "[antirev] decryption failed for '%s'\n", e->name);
            if (ftruncate(fd, 0)) { /* wipe plaintext */ }
            close(fd);
            return 1;
        }
        if (lseek(fd, 0, SEEK_SET) < 0) { perror("lseek memfd"); return 1; }

        main_fd = fd;
    }

    /* Done reading from the binary */
    explicit_bzero(chunk, CHUNK_SIZE);
    free(chunk);
    close(self);

    /* Mode A: no main binary → run as a lightweight lib daemon forever. */
    if (main_fd < 0)
        return run_daemon_forever(real_exe, key, lib_fds, lib_names, &nlibs);

    /* Phase 3. Mode B (daemon libs): fetch lib fds from the daemon. */
    int  daemon_sd = -1;
    char all_enc_names[MAX_FILES][MAX_NAME + 1];
    int  n_all_enc = 0;

    if ((bundle_flags & BFLAG_DAEMON_LIBS) && nlibs == 0) {
        if (fetch_libs_from_daemon(real_exe, envp, key, has_needed_section, n_needed, needed_names, lib_fds, lib_names,
                                   &nlibs, all_enc_names, &n_all_enc, &daemon_sd) < 0)
            return 1;
    }

    /* Wipe key (after daemon socket name derivation) */
    explicit_bzero(key, sizeof(key));

    /* Phase 4. Write embedded shims to memfds.
     *
     * antirev_shim.so hosts both the exe-identity interceptors (readlink
     * / realpath / getauxval …) and the dlopen interceptor — one memfd,
     * one LD_PRELOAD entry.  The aarch64 extend shim stays separate and
     * is materialised below only when building for __aarch64__. */
    int antirev_shim_fd = make_memfd("antirev_shim.so");
    if (antirev_shim_fd < 0)
        return 1;
    if (write_chunk(antirev_shim_fd, antirev_shim_blob, antirev_shim_blob_len) != 0)
        return 1;
    if (lseek(antirev_shim_fd, 0, SEEK_SET) < 0) {
        perror("lseek antirev_shim");
        return 1;
    }

    /* Phase 4b. Split libs into DT_NEEDED (symlink dir) and rest (ANTIREV_FD_MAP).
     *
     * DT_NEEDED libs are resolved by glibc's normal BFS through the symlink
     * dir on LD_LIBRARY_PATH — preserving the original symbol lookup order.
     * They are NOT put on LD_PRELOAD (which would reorder them ahead of
     * unencrypted libs and change symbol resolution).
     *
     * Remaining libs are available on-demand via dlopen_shim + ANTIREV_FD_MAP. */
    int dt_needed_fds[MAX_FILES];
    char dt_needed_names[MAX_FILES][MAX_NAME + 1];
    int n_dt_needed = 0;

    int fdmap_fds[MAX_FILES];
    char fdmap_names[MAX_FILES][MAX_NAME + 1];
    int n_fdmap = 0;

    if (has_needed_section && nlibs > 0) {
        /* Identify which daemon libs are in the exe's DT_NEEDED chain.
         * These go into the symlink dir only (not LD_PRELOAD). */
        for (int k = 0; k < n_needed; k++) {
            for (int j = 0; j < nlibs; j++) {
                if (strcmp(lib_names[j], needed_names[k]) == 0) {
                    dt_needed_fds[n_dt_needed] = lib_fds[j];
                    memcpy(dt_needed_names[n_dt_needed], lib_names[j], MAX_NAME + 1);
                    n_dt_needed++;
                    break;
                }
            }
        }
        /* Remaining libs go to ANTIREV_FD_MAP for on-demand dlopen */
        for (int j = 0; j < nlibs; j++) {
            int is_needed = 0;
            for (int k = 0; k < n_needed; k++) {
                if (strcmp(lib_names[j], needed_names[k]) == 0) {
                    is_needed = 1;
                    break;
                }
            }
            if (!is_needed) {
                fdmap_fds[n_fdmap] = lib_fds[j];
                memcpy(fdmap_names[n_fdmap], lib_names[j], MAX_NAME + 1);
                n_fdmap++;
            }
        }
        fprintf(stderr, "[antirev] split: %d via symlinks, %d on FD_MAP "
                "(needed=%d, daemon=%d)\n",
                n_dt_needed, n_fdmap, n_needed, nlibs);
        for (int k = 0; k < n_dt_needed; k++)
            fprintf(stderr, "[antirev]   DT_NEEDED: %s (fd %d)\n",
                    dt_needed_names[k], dt_needed_fds[k]);
    } else {
        /* No needed list — all libs go on LD_PRELOAD (backward compat).
         * This path is used by old protected binaries without the needed
         * section.  It does NOT preserve original symbol lookup order. */
        n_dt_needed = nlibs;
        memcpy(dt_needed_fds, lib_fds, (size_t)nlibs * sizeof(int));
        memcpy(dt_needed_names, lib_names, (size_t)nlibs * (MAX_NAME + 1));
        fprintf(stderr, "[antirev] backward compat: all %d libs on LD_PRELOAD\n",
                nlibs);
    }

    /* Phase 4c. Create symlink dir for ALL encrypted libs (DT_NEEDED + FD_MAP):
     *   /tmp/antirev_XXXXXX/libfoo.so → /proc/self/fd/N
     *
     * This dir is prepended to LD_LIBRARY_PATH.  For DT_NEEDED libs, this
     * is the PRIMARY resolution mechanism — glibc's BFS finds them here,
     * preserving the original symbol lookup order.  For FD_MAP (dlopen'd)
     * libs, the symlinks serve as a fallback when the lib's own DT_NEEDED
     * chain references other encrypted libs. */
    /* PID-tagged template lets the daemon's startup/shutdown sweep
     * identify which symlink dirs are owned by which protected exe.
     * If our PID is dead by the time the daemon next sweeps, the dir
     * gets reaped — covers the SIGKILL / segfault / hard-crash path
     * that exe_shim's atexit handler can't.  mkdtemp replaces the
     * trailing XXXXXX with random chars and chmods the dir to 0700. */
    char link_dir[64];
    snprintf(link_dir, sizeof(link_dir), "/tmp/antirev_%d_XXXXXX", (int)getpid());
    char *link_dir_ptr = mkdtemp(link_dir);
    if (link_dir_ptr) {
        for (int j = 0; j < n_dt_needed; j++) {
            char lpath[sizeof(link_dir) + MAX_NAME + 2];
            char target[64];
            snprintf(lpath, sizeof(lpath), "%s/%s", link_dir, dt_needed_names[j]);
            snprintf(target, sizeof(target), "/proc/self/fd/%d", dt_needed_fds[j]);
            if (symlink(target, lpath) < 0)
                perror("[antirev] symlink");
        }
        for (int j = 0; j < n_fdmap; j++) {
            char lpath[sizeof(link_dir) + MAX_NAME + 2];
            char target[64];
            snprintf(lpath, sizeof(lpath), "%s/%s", link_dir, fdmap_names[j]);
            snprintf(target, sizeof(target), "/proc/self/fd/%d", fdmap_fds[j]);
            if (symlink(target, lpath) < 0)
                perror("[antirev] symlink");
        }
        fprintf(stderr, "[antirev] symlink dir: %s (%d links)\n",
                link_dir, n_dt_needed + n_fdmap);
    }

    /* Phase 5. Build the envp we'll hand fexecve. */
    char **new_env = build_exec_env(&(exec_env_cfg_t) {
            .envp = envp,
            .real_exe = real_exe,
            .main_fd = main_fd,
            .antirev_shim_fd = antirev_shim_fd,
            .has_needed_section = has_needed_section,
            .nlibs = nlibs,
            .n_dt_needed = n_dt_needed,
            .dt_needed_fds = dt_needed_fds,
            .n_fdmap = n_fdmap,
            .fdmap_names = fdmap_names,
            .fdmap_fds = fdmap_fds,
            .daemon_sd = daemon_sd,
            .n_all_enc = n_all_enc,
            .all_enc_names = all_enc_names,
            .link_dir_ptr = link_dir_ptr,
            .link_dir = link_dir,
    });
    if (!new_env) {
        perror("malloc env");
        return 1;
    }

    /* Phase 6. Replace this process with the decrypted binary. */
    exec_target(main_fd, argv, new_env, real_exe);
    perror("fexecve");
    return 1;
}
