/*
 * antirev stub launcher
 *
 * Appended-bundle format (at end of this binary after protection):
 *   [num_files     : 4 B LE]
 *   [bundle_flags  : 1 B]        bit0 = has_external_libs
 *   for each file:
 *     [name_len : 2 B LE] [name : name_len bytes] [flags : 1 B] (bit0 = is_main)
 *     [iv       : 12 B]
 *     [tag      : 16 B]
 *     [ct_size  : 8 B LE]
 *     [ciphertext : ct_size bytes]
 *   [bundle_start_offset : 8 B LE]   <- offset from file start
 *   [key  : 32 B]                    <- AES-256 key embedded in binary
 *   [magic : 8 B "ANTREV01"]
 *
 * Trailer is always 48 bytes at end of file.
 *
 * Runtime flow (no fork, no disk, O(chunk) peak memory):
 *   Phase 1 — scan bundle headers (tiny reads, skip ciphertext via offset)
 *   Phase 2 — per file, two streaming passes over ciphertext:
 *               Pass A: GHASH  → verify GCM tag (abort on failure)
 *               Pass B: CTR    → decrypt chunk by chunk → write to memfd
 *   Phase 3 — load embedded exe_shim.so into memfd
 *   Phase 4 — fexecve(main_fd) — replaces this process image (same PID)
 *
 * Peak stub heap: one CHUNK_SIZE buffer (~4 MB) + header table (~37 KB max).
 * All plaintext lives only in kernel memfds, never fully in user-space heap.
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/syscall.h>
#include "crypto.h"

#ifndef __NR_memfd_create
#  if defined(__x86_64__)
#    define __NR_memfd_create 319
#  elif defined(__aarch64__)
#    define __NR_memfd_create 279
#  endif
#endif

/* Generated by cmake — arch-specific shim blobs */
#if defined(__aarch64__)
#  include "exe_shim_blob_aarch64.h"     /* exe_shim_blob,    exe_shim_blob_len    */
#else
#  include "exe_shim_blob.h"
#endif

/* ------------------------------------------------------------------ */

#define MAGIC        "ANTREV01"
#define MAGIC_LEN    8
#define KEY_SIZE     32   /* AES-256 */
#define IV_SIZE      12   /* GCM nonce */
#define TAG_SIZE     16   /* GCM auth tag */
#define MAX_NAME     255
#define MAX_FILES    128
#define CHUNK_SIZE   (4 * 1024 * 1024)  /* 4 MB I/O + crypto buffer */

/* ------------------------------------------------------------------ */
/*  Per-file metadata collected during header scan (Phase 1)          */
/* ------------------------------------------------------------------ */
typedef struct {
    char     name[MAX_NAME + 1];
    int      is_main;
    uint8_t  iv[IV_SIZE];
    uint8_t  tag[TAG_SIZE];
    uint64_t ct_size;
    uint64_t ct_offset;   /* byte offset in /proc/self/exe */
} file_entry_t;

/* ------------------------------------------------------------------ */
/*  Little-endian readers                                              */
/* ------------------------------------------------------------------ */
static inline uint16_t u16le(const uint8_t *p)
{
    return (uint16_t)(p[0] | (p[1] << 8));
}
static inline uint32_t u32le(const uint8_t *p)
{
    return p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static inline uint64_t u64le(const uint8_t *p)
{
    uint64_t v = 0;
    for (int i = 0; i < 8; i++) v |= (uint64_t)p[i] << (8 * i);
    return v;
}

/* ------------------------------------------------------------------ */
/*  Write bytes to a new memfd (no O_CLOEXEC — must survive fexecve)  */
/* ------------------------------------------------------------------ */
static int make_memfd(const char *name)
{
    int fd = (int)syscall(__NR_memfd_create, name, 0 /* no MFD_CLOEXEC */);
    if (fd < 0) { perror("memfd_create"); return -1; }
    return fd;
}

static int write_chunk(int fd, const uint8_t *data, size_t len)
{
    for (size_t w = 0; w < len; ) {
        ssize_t n = write(fd, data + w, len - w);
        if (n < 0) { perror("write memfd"); return -1; }
        w += (size_t)n;
    }
    return 0;
}

/* ------------------------------------------------------------------ */
/*  main                                                               */
/* ------------------------------------------------------------------ */
int main(int argc __attribute__((unused)), char *argv[], char *envp[])
{
    /* 1. Capture real exe path before fexecve replaces /proc/self/exe.
     *    Use raw syscall to bypass any inherited LD_PRELOAD exe_shim from
     *    a parent protected binary — we need the true kernel-level path. */
    char real_exe[4096];
    {
        ssize_t n = (ssize_t)syscall(SYS_readlinkat, AT_FDCWD,
                                     "/proc/self/exe", real_exe, sizeof(real_exe) - 1);
        if (n <= 0) { perror("readlink /proc/self/exe"); return 1; }
        real_exe[n] = '\0';
    }

    /* 2. Open /proc/self/exe and read the 48-byte trailer */
    int self = open("/proc/self/exe", O_RDONLY);
    if (self < 0) { perror("open /proc/self/exe"); return 1; }

    off_t fsize = lseek(self, 0, SEEK_END);
    if (fsize < 48) {
        fprintf(stderr, "[antirev] binary too small\n");
        return 1;
    }

    /* Trailer layout: [bundle_offset:8B][key:32B][magic:8B] = 48 bytes */
    uint8_t trailer[48];
    if (pread(self, trailer, 48, fsize - 48) != 48) {
        perror("pread trailer"); return 1;
    }
    if (memcmp(trailer + 40, MAGIC, MAGIC_LEN) != 0) {
        fprintf(stderr, "[antirev] not a protected binary (magic not found)\n");
        return 1;
    }

    uint64_t bundle_off = u64le(trailer);

    /* 2. Extract key from trailer */
    uint8_t key[KEY_SIZE];
    memcpy(key, trailer + 8, KEY_SIZE);

    /* ----------------------------------------------------------------
     * Phase 1: scan bundle headers — collect metadata for every file.
     * We only read the tiny per-file headers; ciphertext is skipped via
     * offset arithmetic and never loaded into user-space memory here.
     * ---------------------------------------------------------------- */
    uint8_t tmp[2 + MAX_NAME + 1 + IV_SIZE + TAG_SIZE + 8]; /* max header */

    /* Read num_files (4 bytes) + bundle_flags (1 byte) */
    if (pread(self, tmp, 5, (off_t)bundle_off) != 5) {
        perror("pread num_files"); return 1;
    }
    uint32_t nfiles = u32le(tmp);
    /* uint8_t bundle_flags = tmp[4]; — reserved for future use */
    if (nfiles > MAX_FILES) {
        fprintf(stderr, "[antirev] too many files in bundle (%u)\n", nfiles);
        return 1;
    }

    file_entry_t entries[MAX_FILES];
    off_t scan = (off_t)bundle_off + 5;

    for (uint32_t i = 0; i < nfiles; i++) {
        file_entry_t *e = &entries[i];

        /* name_len (2 bytes) */
        if (pread(self, tmp, 2, scan) != 2) { perror("pread name_len"); return 1; }
        uint16_t nlen = u16le(tmp);
        if (nlen > MAX_NAME) {
            fprintf(stderr, "[antirev] name too long in bundle\n");
            return 1;
        }
        scan += 2;

        /* name + flags + iv + tag + ct_size */
        ssize_t hdr_rest = nlen + 1 + IV_SIZE + TAG_SIZE + 8;
        if (pread(self, tmp, (size_t)hdr_rest, scan) != hdr_rest) {
            perror("pread file header"); return 1;
        }
        memcpy(e->name, tmp, nlen);
        e->name[nlen]  = '\0';
        e->is_main     = tmp[nlen] & 1;
        memcpy(e->iv,  tmp + nlen + 1,                     IV_SIZE);
        memcpy(e->tag, tmp + nlen + 1 + IV_SIZE,           TAG_SIZE);
        e->ct_size     = u64le(tmp + nlen + 1 + IV_SIZE + TAG_SIZE);
        scan          += hdr_rest;

        e->ct_offset   = (uint64_t)scan;
        scan          += (off_t)e->ct_size;

        /* Sanity: ciphertext must not overlap the trailer */
        if (e->ct_offset + e->ct_size > (uint64_t)(fsize - 48)) {
            fprintf(stderr, "[antirev] bundle extends past trailer\n");
            return 1;
        }
    }

    /* ----------------------------------------------------------------
     * Phase 2: for each file, stream two passes over the ciphertext.
     *   Pass A — GHASH accumulation → tag verification
     *   Pass B — CTR decryption chunk by chunk → write to memfd
     *
     * Peak user-space heap: one CHUNK_SIZE buffer.
     * ---------------------------------------------------------------- */
    uint8_t *chunk = malloc(CHUNK_SIZE);
    if (!chunk) { perror("malloc chunk"); return 1; }

    int main_fd = -1;

    for (uint32_t i = 0; i < nfiles; i++) {
        file_entry_t *e = &entries[i];
        aes256gcm_ctx ctx;

        /* --- Pass A: GHASH --- */
        aes256gcm_init(&ctx, key, e->iv);
        uint64_t remaining = e->ct_size;
        off_t    pos       = (off_t)e->ct_offset;
        while (remaining > 0) {
            size_t  to_read = (remaining < CHUNK_SIZE) ? (size_t)remaining : CHUNK_SIZE;
            ssize_t got     = pread(self, chunk, to_read, pos);
            if (got != (ssize_t)to_read) { perror("pread ciphertext"); return 1; }
            aes256gcm_ghash_update(&ctx, chunk, to_read);
            pos       += (off_t)to_read;
            remaining -= to_read;
        }
        if (aes256gcm_ghash_verify(&ctx, e->tag) != 0) {
            fprintf(stderr, "[antirev] decryption failed for '%s'\n", e->name);
            return 1;
        }

        if (!e->is_main) continue;  /* only decrypt the main exe */

        /* --- Pass B: CTR decrypt + write to memfd --- */
        int fd = make_memfd(e->name);
        if (fd < 0) return 1;

        aes256gcm_init(&ctx, key, e->iv);  /* reset counter for decryption pass */
        remaining = e->ct_size;
        pos       = (off_t)e->ct_offset;
        while (remaining > 0) {
            size_t  to_read = (remaining < CHUNK_SIZE) ? (size_t)remaining : CHUNK_SIZE;
            ssize_t got     = pread(self, chunk, to_read, pos);
            if (got != (ssize_t)to_read) { perror("pread ciphertext"); return 1; }
            aes256gcm_ctr_decrypt(&ctx, chunk, chunk, to_read); /* in-place */
            if (write_chunk(fd, chunk, to_read) != 0) return 1;
            pos       += (off_t)to_read;
            remaining -= to_read;
        }
        if (lseek(fd, 0, SEEK_SET) < 0) { perror("lseek memfd"); return 1; }

        main_fd = fd;
    }

    if (main_fd < 0) {
        fprintf(stderr, "[antirev] no main binary in bundle\n");
        return 1;
    }

    /* Wipe key and chunk buffer */
    explicit_bzero(key,   sizeof(key));
    explicit_bzero(chunk, CHUNK_SIZE);
    free(chunk);
    close(self);

    /* 5. Write embedded exe shim to memfd */
    int exe_shim_fd = make_memfd("antirev_exe_shim.so");
    if (exe_shim_fd < 0) return 1;
    if (write_chunk(exe_shim_fd, exe_shim_blob, exe_shim_blob_len) != 0) return 1;
    if (lseek(exe_shim_fd, 0, SEEK_SET) < 0) { perror("lseek exe_shim"); return 1; }

    /* 6. Build new envp */
    int envc = 0;
    while (envp[envc]) envc++;

    /* Find existing LD_PRELOAD to preserve it */
    const char *existing_preload = NULL;
    for (int j = 0; j < envc; j++) {
        if (strncmp(envp[j], "LD_PRELOAD=", 11) == 0) {
            existing_preload = envp[j] + 11;
            break;
        }
    }

    /* +4: REAL_EXE, MAIN_FD, LD_PRELOAD, NULL */
    char **new_env = malloc((size_t)(envc + 4) * sizeof(char *));
    if (!new_env) { perror("malloc env"); return 1; }

    char real_exe_entry[4096 + 32];
    char main_fd_entry[32];

    snprintf(real_exe_entry, sizeof(real_exe_entry),
             "ANTIREV_REAL_EXE=%s", real_exe);
    snprintf(main_fd_entry, sizeof(main_fd_entry),
             "ANTIREV_MAIN_FD=%d", main_fd);

    /* Prepend our exe shim to any existing LD_PRELOAD entries */
    size_t preload_len = 64 + (existing_preload ? 1 + strlen(existing_preload) : 0);
    char *ld_preload_entry = malloc(preload_len);
    if (!ld_preload_entry) { perror("malloc ld_preload"); return 1; }
    if (existing_preload)
        snprintf(ld_preload_entry, preload_len,
                 "LD_PRELOAD=/proc/self/fd/%d:%s", exe_shim_fd, existing_preload);
    else
        snprintf(ld_preload_entry, preload_len,
                 "LD_PRELOAD=/proc/self/fd/%d", exe_shim_fd);

    int ei = 0;
    for (int j = 0; j < envc; j++) {
        if (strncmp(envp[j], "LD_PRELOAD=",       11) == 0) continue;
        if (strncmp(envp[j], "ANTIREV_REAL_EXE=", 17) == 0) continue;
        if (strncmp(envp[j], "ANTIREV_MAIN_FD=",  16) == 0) continue;
        new_env[ei++] = envp[j];
    }
    new_env[ei++] = real_exe_entry;
    new_env[ei++] = main_fd_entry;
    new_env[ei++] = ld_preload_entry;
    new_env[ei]   = NULL;

    /* 7. Replace this process with the decrypted binary — no fork, same PID */
    fexecve(main_fd, argv, new_env);
    perror("fexecve");
    return 1;
}
