PACKAGE_NAME="vcachefs"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="vcachefs"
DEST_MODULE_LOCATION[0]="/kernel/fs/vcachefs"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"

AUTOINSTALL="yes"
# Rebuild automatically on every kernel upgrade (DKMS post-install hook).
REMAKE_INITRD="no"
