/*
 * gate_trusted_hashes.h — GENERATED by authz-embed-qemu-hash.sh.  Do not hand-
 * edit unless adding more pinned entries.  Pins a caller build by name + exact
 * SHA-256 (see the module's gate.c authz_hash_check).  Rebuild the module after
 * regenerating.  Source binary: kmod2/qemu-gate/prebuilt/qemu-aarch64-static
 */
#ifndef ANTIREVFS_GATE_TRUSTED_HASHES_H
#define ANTIREVFS_GATE_TRUSTED_HASHES_H

struct arev_trusted_hash {
	const char	*name;
	unsigned char	sha256[32];
};

static const struct arev_trusted_hash arev_trusted_hashes[] = {
	{ "qemu-aarch64-static", {
		0xe1, 0x5a, 0x16, 0xbe, 0x5a, 0x29, 0xc7, 0x41,
		0x09, 0x57, 0x94, 0x04, 0xad, 0x28, 0x5b, 0x93,
		0x7d, 0x20, 0x8c, 0x6b, 0xce, 0xf5, 0xfb, 0xee,
		0xd4, 0x95, 0xc8, 0xe4, 0x44, 0xcc, 0x19, 0xdb,	} },
	{ NULL, { 0 } },
};

#endif /* ANTIREVFS_GATE_TRUSTED_HASHES_H */
