#!/usr/bin/env python3
"""Generate key_blob.c: the obfuscated AES-256 master key compiled into the
vcachefs .ko (kmod2) or the vcachefsd binary (fusefs).

Reads a hex keyfile (64 hex chars = 32 bytes), XORs each byte with obf_key(i)
(the SAME per-position formula as shared/obfstr_gen.py), and writes a C source
defining vcf_master_key_present=1 and vcf_master_key_obf[32].  The consumer
de-obfuscates at runtime (vcf_get_master_key in crypto.c).

Usage: gen_key_blob.py <keyfile.hex> <out.c>
"""
import sys
from pathlib import Path


def obf_key(i: int) -> int:
    # KEEP IN SYNC with obf_key() in shared/obfstr_gen.py and the runtime loops
    # in kmod2/module/crypto.c and fusefs/src/crypto.c.
    return 0x5a ^ (((i * 7) + 13) & 0xff)


def main(argv):
    if len(argv) != 3:
        sys.exit("usage: gen_key_blob.py <keyfile.hex> <out.c>")
    try:
        key = bytes.fromhex(Path(argv[1]).read_text().strip())
    except (ValueError, OSError) as e:
        sys.exit(f"[gen_key_blob] cannot read hex key from {argv[1]}: {e}")
    if len(key) != 32:
        sys.exit(f"[gen_key_blob] key must be 32 bytes (AES-256); got {len(key)}")
    obf = ', '.join(f'0x{(b ^ obf_key(i)) & 0xff:02x}' for i, b in enumerate(key))
    Path(argv[2]).write_text(
        "// SPDX-License-Identifier: GPL-2.0\n"
        "/* GENERATED by shared/gen_key_blob.py from a project keyfile - DO NOT EDIT.\n"
        " * Obfuscated AES-256 master key (each byte XOR obf_key(i)); de-obfuscated\n"
        " * at runtime by vcf_get_master_key(). */\n"
        "#ifdef __KERNEL__\n#include <linux/types.h>\n#endif\n\n"
        "const int vcf_master_key_present = 1;\n"
        f"const unsigned char vcf_master_key_obf[32] = {{ {obf} }};\n"
    )
    print(f"[gen_key_blob] embedded 32-byte key into {argv[2]}")


if __name__ == '__main__':
    main(sys.argv)
