#!/usr/bin/env python3
"""
gen_obf.py — generate the obfuscated-string header consumed by stub/obf.h.

Reads the canonical list of sensitive strings from this file, encodes each
one with a per-build XOR key + position offset + salt, and emits a header
with `static const unsigned char OBF_DATA_<NAME>[]` arrays + length defines.

The header is included by stub/obf.h, which provides the OBF(NAME) macro
that decodes into a per-thread static buffer at use site.

Usage:
    gen_obf.py <output_header_path>

Per-build randomization: set ANTIREV_OBF_SEED=<int> for reproducible builds
(e.g. release pipelines that want deterministic outputs). Otherwise a fresh
seed is drawn per invocation, which means a published deobfuscator for one
release won't trivially work against the next.
"""

import os
import secrets
import sys
from pathlib import Path

# ── Single source of truth for sensitive strings. ─────────────────────
# Add new strings here, reference them in C as OBF(<NAME>).
STRINGS = {
    # Magic header for protected payloads
    "MAGIC_HEADER":            "ANTREV01",

    # Environment variable names — every ANTIREV_* control surface
    "ENV_FD_MAP":              "ANTIREV_FD_MAP",
    "ENV_LIBD_SOCK":           "ANTIREV_LIBD_SOCK",
    "ENV_ENC_LIBS":            "ANTIREV_ENC_LIBS",
    "ENV_SYMLINK_DIR":         "ANTIREV_SYMLINK_DIR",
    "ENV_CLOSE_FDS":           "ANTIREV_CLOSE_FDS",
    "ENV_DLOPEN_LOG":          "ANTIREV_DLOPEN_LOG",
    "ENV_AARCH64_EXTEND_LOG":  "ANTIREV_AARCH64_EXTEND_LOG",
    "ENV_NO_PRELOAD":          "ANTIREV_NO_PRELOAD",
    "ENV_REAL_EXE":            "ANTIREV_REAL_EXE",
    "ENV_MAIN_FD":             "ANTIREV_MAIN_FD",
    "ENV_LD_PRELOAD":          "LD_PRELOAD",
    "ENV_LD_LIBRARY_PATH":     "LD_LIBRARY_PATH",
    "ENV_PREFIX_ANTIREV":      "ANTIREV_",  # used in startswith() checks

    # Filesystem paths used during identity hide / fd lookup
    "PATH_PROC_SELF_EXE":      "/proc/self/exe",
    "PATH_PROC_SELF_FD_DIR":   "/proc/self/fd/",
    "PATH_PROC_SELF_AUXV":     "/proc/self/auxv",

    # Symlink-dir + tmpfs prefix
    "PREFIX_SYMLINK_DIR":      "/tmp/antirev_",

    # Daemon socket basenames (per-arch + generic fallback)
    "DAEMON_BIN_NAME":         "/.antirev-libd",
    "DAEMON_BIN_NAME_X86":     "/.antirev-libd-x86_64",
    "DAEMON_BIN_NAME_ARM":     "/.antirev-libd-aarch64",

    # Lower-case "antirev_" prefix — used as the abstract Unix-socket
    # name prefix and the sweep-dir basename prefix.  Distinct from
    # ENV_PREFIX_ANTIREV ("ANTIREV_") which lives in env-var land.
    "PREFIX_LOWER_ANTIREV":    "antirev_",

    # memfd name set on the shim DSO so the kernel-visible
    # /proc/<pid>/fd/N readlink returns "memfd:<this>".
    "SHIM_MEMFD_NAME":         "antirev_shim.so",

    # memfd identity probe needle
    "MEMFD_NEEDLE":            "memfd:",

    # Format-string fragments that reveal layout
    "FMT_PROC_SELF_FD_D":      "/proc/self/fd/%d",
    "FMT_PROC_SELF_FD_S":      "/proc/self/fd/%s",
}


def encode(plaintext: str, key: int, salt: int) -> bytes:
    """XOR each byte with (key + position + salt) mod 256, including NUL."""
    out = bytearray()
    for i, b in enumerate(plaintext.encode("utf-8") + b"\x00"):
        out.append(b ^ ((key + i + salt) & 0xFF))
    return bytes(out)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: gen_obf.py <output_header_path>", file=sys.stderr)
        return 2

    out_path = Path(argv[1])

    # Per-build randomization (override with ANTIREV_OBF_SEED for repro builds).
    seed_env = os.environ.get("ANTIREV_OBF_SEED")
    if seed_env:
        seed = int(seed_env, 0)
    else:
        seed = secrets.randbits(32)

    # Force key non-zero so 0x00 plaintext bytes don't pass through.
    key = (seed & 0xFF) or 0x42
    salt = (seed >> 8) & 0xFF

    lines: list[str] = []
    lines.append("/* Auto-generated by tools/gen_obf.py — DO NOT EDIT. */")
    lines.append("#ifndef ANTIREV_OBF_STRINGS_DATA_H")
    lines.append("#define ANTIREV_OBF_STRINGS_DATA_H")
    lines.append("")
    lines.append(f"#define OBF_KEY  0x{key:02x}")
    lines.append(f"#define OBF_SALT 0x{salt:02x}")
    lines.append("")
    for name, plaintext in STRINGS.items():
        enc = encode(plaintext, key, salt)
        bytes_str = ", ".join(f"0x{b:02x}" for b in enc)
        lines.append(f"#define OBF_LEN_{name} {len(plaintext)}")
        lines.append(
            f"static const unsigned char OBF_DATA_{name}[{len(enc)}] = "
            f"{{ {bytes_str} }};"
        )
        lines.append("")
    lines.append("#endif /* ANTIREV_OBF_STRINGS_DATA_H */")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines))

    print(
        f"[gen_obf] {out_path} (seed=0x{seed:08x}, key=0x{key:02x}, "
        f"salt=0x{salt:02x}, {len(STRINGS)} strings)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
