#!/usr/bin/env python3
"""
cmake/bin2h.py — convert a binary file to a C header with a static byte array.

Usage: python3 bin2h.py <input_file> <output_header> <variable_name>
"""
import sys

if len(sys.argv) != 4:
    sys.exit("Usage: bin2h.py <input> <output.h> <varname>")

_, inp, out, varname = sys.argv

data = open(inp, "rb").read()

rows = []
for i in range(0, len(data), 16):
    chunk = data[i:i+16]
    rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

header = f"""\
/* Auto-generated by cmake/bin2h.py — do not edit */
static const unsigned char {varname}[] = {{
{chr(10).join(rows)}
}};
static const unsigned int {varname}_len = {len(data)}u;
"""

open(out, "w").write(header)
print(f"[bin2h] {inp} → {out}  ({len(data):,} bytes)")
