#!/usr/bin/env bash
# authz-embed-pubkey.sh — turn the DER cert into module/gate_authz_pubkey.h.
#
#   ./authz-embed-pubkey.sh authz_cert.der > ../module/gate_authz_pubkey.h
#   (then rebuild the module)
set -euo pipefail
DER="${1:?usage: authz-embed-pubkey.sh <cert.der> > gate_authz_pubkey.h}"
[ -s "$DER" ] || { echo "empty/missing DER: $DER" >&2; exit 1; }
LEN=$(wc -c < "$DER" | tr -d ' ')

printf '/* GENERATED by authz-embed-pubkey.sh from %s — do not edit by hand. */\n' "$(basename "$DER")"
printf '#ifndef ANTIREVFS_GATE_AUTHZ_PUBKEY_H\n#define ANTIREVFS_GATE_AUTHZ_PUBKEY_H\n\n'
printf 'static const unsigned char antirev_authz_cert_der[] = {\n'
# 12 bytes per line, "0xNN, " each — portable (od, no xxd dependency)
od -An -v -tx1 "$DER" | tr -s ' ' '\n' | grep -v '^$' \
  | awk '{ printf "0x%s, ", $1; if (++n % 12 == 0) printf "\n" } END { if (n % 12) printf "\n" }' \
  | sed 's/^/\t/'
printf '};\n'
printf 'static const unsigned int antirev_authz_cert_der_len = %s;\n\n' "$LEN"
printf '#endif /* ANTIREVFS_GATE_AUTHZ_PUBKEY_H */\n'
