#!/usr/bin/env bash
# authz-embed-pubkey.sh — turn the DER cert into module/gate_authz_pubkey.h.
#
#   ./authz-embed-pubkey.sh authz_cert.der ../module/gate_authz_pubkey.h   # SAFE: atomic write
#   ./authz-embed-pubkey.sh authz_cert.der > ../module/gate_authz_pubkey.h # legacy (see WARNING)
#   (then rebuild the module)
#
# WARNING about the `>` form: the shell truncates the target to 0 bytes BEFORE
# this script runs, so if the DER is missing/empty the header is left EMPTY and
# the module fails to build ("antirev_authz_cert_der_len undeclared").  PREFER
# passing the output path as $2 — the header is written atomically (temp + mv)
# and is never clobbered on failure.
set -euo pipefail
DER="${1:?usage: authz-embed-pubkey.sh <cert.der> [out.h]  (out.h recommended over > redirect)}"
OUT="${2:-}"
[ -s "$DER" ] || { echo "empty/missing DER: $DER" >&2; exit 1; }
LEN=$(wc -c < "$DER" | tr -d ' ')

# Buffer the whole header, then emit atomically ($2) or to stdout (legacy).
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
exec 3>&1 1>"$TMP"    # redirect the generation below into the temp buffer

printf '/* GENERATED by authz-embed-pubkey.sh from %s — do not edit by hand. */\n' "$(basename "$DER")"
printf '#ifndef ANTIREVFS_GATE_AUTHZ_PUBKEY_H\n#define ANTIREVFS_GATE_AUTHZ_PUBKEY_H\n\n'
printf 'static const unsigned char antirev_authz_cert_der[] = {\n'
# 12 bytes per line, "0xNN, " each — portable (od, no xxd dependency)
od -An -v -tx1 "$DER" | tr -s ' ' '\n' | grep -v '^$' \
  | awk '{ printf "0x%s, ", $1; if (++n % 12 == 0) printf "\n" } END { if (n % 12) printf "\n" }' \
  | sed 's/^/\t/'
printf '};\n'
printf 'static const unsigned int antirev_authz_cert_der_len = %s;\n\n' "$LEN"
printf '#endif /* ANTIREVFS_GATE_AUTHZ_PUBKEY_H */\n'

# Restore real stdout; the full header now sits in $TMP.  Only NOW commit it:
# to $OUT via an atomic rename (never a half-written/empty header), or to stdout
# for the legacy `> file` form.
exec 1>&3 3>&-
if [ -n "$OUT" ]; then
	mv -f "$TMP" "$OUT"
	trap - EXIT
	echo "wrote $OUT ($LEN-byte cert embedded)" >&2
else
	cat "$TMP"
fi
