#!/bin/sh
# authz-embed-qemu-hash.sh — pin a trusted caller build by name + SHA-256.
#
# Regenerates kmod2/module/gate_trusted_hashes.h so the kernel gate trusts ONE
# specific binary (e.g. your gate-enabled qemu-aarch64-static) instead of any
# file that merely shares the basename.  Rebuild the module after running this.
#
# Usage:
#   authz-embed-qemu-hash.sh <binary> [basename] <out-header>
#     <binary>     the exact file to pin (its SHA-256 is embedded)
#     [basename]   name the gate matches at runtime (default: basename <binary>)
#     <out-header> path to gate_trusted_hashes.h (written atomically)
#
# To pin MULTIPLE builds/arches, run once per binary is NOT enough (this writes a
# single-entry header); instead edit the generated header and add more { name,
# {..} } rows, or extend this script.  Written atomically (temp + mv) so a
# failure never truncates the header (cf. the authz-embed-pubkey.sh gotcha).
set -eu

if [ $# -eq 2 ]; then
	BIN=$1; NAME=$(basename "$1"); OUT=$2
elif [ $# -eq 3 ]; then
	BIN=$1; NAME=$2; OUT=$3
else
	echo "usage: $0 <binary> [basename] <out-header>" >&2
	exit 2
fi

[ -r "$BIN" ] || { echo "error: cannot read $BIN" >&2; exit 1; }

# 32-byte SHA-256 as lowercase hex (portable: sha256sum or 'shasum -a 256').
if command -v sha256sum >/dev/null 2>&1; then
	HEX=$(sha256sum "$BIN" | cut -d' ' -f1)
elif command -v shasum >/dev/null 2>&1; then
	HEX=$(shasum -a 256 "$BIN" | cut -d' ' -f1)
else
	echo "error: need sha256sum or shasum" >&2; exit 1
fi
[ "${#HEX}" -eq 64 ] || { echo "error: bad digest '$HEX'" >&2; exit 1; }

# Emit the 32 bytes as C hex initialisers, 8 per line.
BYTES=$(printf '%s\n' "$HEX" | sed -E 's/(..)/0x\1, /g')

TMP=$(mktemp "${OUT}.XXXXXX")
trap 'rm -f "$TMP"' EXIT
{
	cat <<H
/*
 * gate_trusted_hashes.h — GENERATED by authz-embed-qemu-hash.sh.  Do not hand-
 * edit unless adding more pinned entries.  Pins a caller build by name + exact
 * SHA-256 (see the module's gate.c authz_hash_check).  Rebuild the module after
 * regenerating.  Source binary: $BIN
 */
#ifndef ANTIREVFS_GATE_TRUSTED_HASHES_H
#define ANTIREVFS_GATE_TRUSTED_HASHES_H

struct arev_trusted_hash {
	const char	*name;
	unsigned char	sha256[32];
};

static const struct arev_trusted_hash arev_trusted_hashes[] = {
	{ "$NAME", {
H
	printf '%s' "$BYTES" | fold -s -w 48 | sed 's/^/\t\t/; s/ $//'
	cat <<H
	} },
	{ NULL, { 0 } },
};

#endif /* ANTIREVFS_GATE_TRUSTED_HASHES_H */
H
} > "$TMP"
mv "$TMP" "$OUT"
trap - EXIT
echo "pinned '$NAME' = $HEX"
echo "wrote $OUT — rebuild the module."
